// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: techbridge/ap/metering/v1/activity.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-03 14:32:42 UTC

package metering

const (
	// ActivitiesService_CreateActivity_FullMethodDescription returns the description of the techbridge.ap.metering.v1.ActivitiesService.CreateActivity method.
	ActivitiesService_CreateActivity_FullMethodDescription = ""
	// ActivitiesService_BatchCreateActivities_FullMethodDescription returns the description of the techbridge.ap.metering.v1.ActivitiesService.BatchCreateActivities method.
	ActivitiesService_BatchCreateActivities_FullMethodDescription = ""
	// ActivitiesService_GetActivity_FullMethodDescription returns the description of the techbridge.ap.metering.v1.ActivitiesService.GetActivity method.
	ActivitiesService_GetActivity_FullMethodDescription = ""
	// ActivitiesService_ListActivities_FullMethodDescription returns the description of the techbridge.ap.metering.v1.ActivitiesService.ListActivities method.
	ActivitiesService_ListActivities_FullMethodDescription = ""
	// ActivitiesService_AggregateActivities_FullMethodDescription returns the description of the techbridge.ap.metering.v1.ActivitiesService.AggregateActivities method.
	ActivitiesService_AggregateActivities_FullMethodDescription = ""
	// ActivitiesService_StreamListActivities_FullMethodDescription returns the description of the techbridge.ap.metering.v1.ActivitiesService.StreamListActivities method.
	ActivitiesService_StreamListActivities_FullMethodDescription = ""
)
