// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: techbridge/ap/metering/v1/activity.proto

package metering

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The provider that billed for a call.
type Activity_Provider int32

const (
	// Provider not specified.
	Activity_PROVIDER_UNSPECIFIED Activity_Provider = 0
	// Google Vertex AI. The only provider whose charges can be reconciled
	// against a Google invoice.
	Activity_VERTEX_AI Activity_Provider = 1
	// Anthropic, called directly rather than through Vertex AI.
	Activity_ANTHROPIC Activity_Provider = 2
	// OpenAI.
	Activity_OPENAI Activity_Provider = 3
	// Perplexity.
	Activity_PERPLEXITY Activity_Provider = 4
)

// Enum value maps for Activity_Provider.
var (
	Activity_Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "VERTEX_AI",
		2: "ANTHROPIC",
		3: "OPENAI",
		4: "PERPLEXITY",
	}
	Activity_Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"VERTEX_AI":            1,
		"ANTHROPIC":            2,
		"OPENAI":               3,
		"PERPLEXITY":           4,
	}
)

func (x Activity_Provider) Enum() *Activity_Provider {
	p := new(Activity_Provider)
	*p = x
	return p
}

func (x Activity_Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Activity_Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_techbridge_ap_metering_v1_activity_proto_enumTypes[0].Descriptor()
}

func (Activity_Provider) Type() protoreflect.EnumType {
	return &file_techbridge_ap_metering_v1_activity_proto_enumTypes[0]
}

func (x Activity_Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Activity_Provider.Descriptor instead.
func (Activity_Provider) EnumDescriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{0, 0}
}

// How a call ended.
type Activity_Status int32

const (
	// Status not specified.
	Activity_STATUS_UNSPECIFIED Activity_Status = 0
	// The call completed.
	Activity_OK Activity_Status = 1
	// The call failed. Cost is still recorded, because a provider charges for
	// work done before a failure.
	Activity_FAILED Activity_Status = 2
	// The call was refused before it reached the provider, by a spend limit or
	// a guardrail. Usually costs nothing, but is recorded so that refusals are
	// countable.
	Activity_DENIED Activity_Status = 3
	// The call was cut short, by a token limit or a deadline. Partial work was
	// done and is charged for.
	Activity_TRUNCATED Activity_Status = 4
)

// Enum value maps for Activity_Status.
var (
	Activity_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "OK",
		2: "FAILED",
		3: "DENIED",
		4: "TRUNCATED",
	}
	Activity_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"OK":                 1,
		"FAILED":             2,
		"DENIED":             3,
		"TRUNCATED":          4,
	}
)

func (x Activity_Status) Enum() *Activity_Status {
	p := new(Activity_Status)
	*p = x
	return p
}

func (x Activity_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Activity_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_techbridge_ap_metering_v1_activity_proto_enumTypes[1].Descriptor()
}

func (Activity_Status) Type() protoreflect.EnumType {
	return &file_techbridge_ap_metering_v1_activity_proto_enumTypes[1]
}

func (x Activity_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Activity_Status.Descriptor instead.
func (Activity_Status) EnumDescriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{0, 1}
}

// One priced unit of agent work.
type Activity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the activity.
	// Format: `organisations/{organisation}/workspaces/{workspace}/activities/{activity}`
	//
	// The workspace in it is whose the spend is, and it comes from the `parent` the batch was recorded under rather than from any field here, so there is one place a record's tenant is stated and no way for the two to disagree.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The agent that performed the work.
	// Format: `organisations/{organisation}/agents/{agent}`
	//
	// A registered resource rather than a free string, so that spend can always
	// be attributed to something with a known owner.
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	// Opaque identifier of the end-user request this activity belongs to.
	//
	// Every activity produced while serving one user request carries the same
	// value, including across a handoff from one agent to another. This is what
	// makes cost per unit of business work possible: outcomes attach to the
	// request, and the request's activities sum to its cost.
	Request string `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	// Opaque identifier of the conversation or session, where the product has
	// one. Empty for work that is not conversational.
	Session string `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	// Opaque identifier of the person the work was done for.
	//
	// An identifier, never an email or a name. Recorders take it from the
	// verified request context rather than accepting it as an argument, so that
	// one person's spend cannot be attributed to another.
	//
	// The name behind it, where the organisation supplies one, is held once at
	// `organisations/{organisation}/users/{user}` with this value as the last
	// segment, so it cannot contain `/`.
	User string `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	// The service that made the call, e.g. `atlas-agent`, `deep-research`.
	CallerService string `protobuf:"bytes,6,opt,name=caller_service,json=callerService,proto3" json:"caller_service,omitempty"`
	// The part of the calling service that spent the money, e.g. `chat_turn`,
	// `tool:web_search`, `research_merger`.
	//
	// Derived by the recorder from the surrounding framework call, so adopting
	// teams do not set it per call site. A free string on the wire: adding a new
	// component never requires a contract change. Values an agent did not
	// declare in `Agent.components` are still accepted, and reported, so that
	// drift is visible rather than silent.
	CallerComponent string `protobuf:"bytes,7,opt,name=caller_component,json=callerComponent,proto3" json:"caller_component,omitempty"`
	// The area of the product the person was using, e.g. `canvas`,
	// `doc_viewer`, `social`.
	//
	// Distinct from `caller_component`, which is a code path. This is a product
	// concept the framework cannot infer, so it is set once on the request
	// context by products that want to slice cost this way, and left empty
	// otherwise.
	Skill string `protobuf:"bytes,8,opt,name=skill,proto3" json:"skill,omitempty"`
	// The model that was called, as the provider names it,
	// e.g. `gemini-2.5-pro`.
	Model string `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	// The provider that billed for the call.
	Provider Activity_Provider `protobuf:"varint,10,opt,name=provider,proto3,enum=techbridge.ap.metering.v1.Activity_Provider" json:"provider,omitempty"`
	// Tokens in the prompt.
	PromptTokens int32 `protobuf:"varint,11,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	// Tokens the model generated.
	CandidateTokens int32 `protobuf:"varint,12,opt,name=candidate_tokens,json=candidateTokens,proto3" json:"candidate_tokens,omitempty"`
	// Prompt tokens served from the provider's cache, which are usually billed
	// at a different rate from ordinary prompt tokens. Counted separately so the
	// rate card can price them correctly.
	CachedTokens int32 `protobuf:"varint,13,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	// Prompt tokens written to the provider's cache. Some providers bill a
	// premium for this, so it is priced separately rather than folded into
	// `prompt_tokens`.
	CacheWriteTokens int32 `protobuf:"varint,14,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	// Tokens the model spent reasoning, where the provider reports them apart
	// from the visible response.
	ReasoningTokens int32 `protobuf:"varint,15,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	// Total tokens the provider reported for the call. Recorded as reported
	// rather than summed locally, so the figure can be checked against the
	// provider.
	TotalTokens int32 `protobuf:"varint,16,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	// What the call is expected to cost, in millionths of a US dollar.
	//
	// Computed by the server from token counts, `charges` and the rate card in
	// force at `occurred_at`. Available immediately, and approximate. Money is
	// an integer count of millionths rather than a floating-point amount so that
	// sums are exact.
	EstimatedCostMicros int64 `protobuf:"varint,17,opt,name=estimated_cost_micros,json=estimatedCostMicros,proto3" json:"estimated_cost_micros,omitempty"`
	// What the call was actually billed, in millionths of a US dollar.
	//
	// Written by the nightly reconciliation from the cloud billing export, and
	// zero until that has run. Only populated for charges that appear on a
	// Google invoice; a provider called directly is never reconciled, and this
	// stays zero for those. Where both figures are present, this one is the
	// truth and `estimated_cost_micros` is the estimate it corrected.
	BilledCostMicros int64 `protobuf:"varint,18,opt,name=billed_cost_micros,json=billedCostMicros,proto3" json:"billed_cost_micros,omitempty"`
	// The version of the rate card used to price this activity.
	//
	// Recorded so that a later change to provider pricing does not silently
	// rewrite what history cost.
	RateCardVersion string `protobuf:"bytes,19,opt,name=rate_card_version,json=rateCardVersion,proto3" json:"rate_card_version,omitempty"`
	// Charges not measured in tokens, such as a per-request search fee.
	//
	// Repeated because one call can incur several. A token-only call has none.
	Charges []*Charge `protobuf:"bytes,20,rep,name=charges,proto3" json:"charges,omitempty"`
	// How long the call took, in milliseconds.
	DurationMs int64 `protobuf:"varint,21,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// How the call ended.
	Status Activity_Status `protobuf:"varint,22,opt,name=status,proto3,enum=techbridge.ap.metering.v1.Activity_Status" json:"status,omitempty"`
	// The provider or platform error code, where the call did not succeed.
	//
	// A code, never a message: provider exception messages can quote the prompt.
	ErrorCode string `protobuf:"bytes,23,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// The unit of work inside a workspace that this call served, e.g. `acme-q3-refresh`, `matter-1183`.
	//
	// A product's own identifier for a piece of work, set once on the request context beside the person, and empty for a product that has no such concept. Grouped and filtered like any other dimension.
	//
	// A label and never a boundary: it is not part of any resource name, nothing is authorised against it, and an unrecognised value is accepted and reported rather than refused. Everyone who can read the workspace can read every project in it, so a project must never be used to keep one reader away from another's figures.
	Project string `protobuf:"bytes,25,opt,name=project,proto3" json:"project,omitempty"`
	// When the work happened, as reported by the recorder.
	//
	// Preserved as supplied. The server falls back to its own clock only when
	// this is omitted, so that a batch delayed in transit is still priced and
	// reported against the time it actually occurred.
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Entity tag.
	Etag string `protobuf:"bytes,97,opt,name=etag,proto3" json:"etag,omitempty"`
	// When this activity was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When this activity was last updated, which for most activities is when
	// reconciliation wrote `billed_cost_micros`.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{0}
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Activity) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Activity) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Activity) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Activity) GetCallerService() string {
	if x != nil {
		return x.CallerService
	}
	return ""
}

func (x *Activity) GetCallerComponent() string {
	if x != nil {
		return x.CallerComponent
	}
	return ""
}

func (x *Activity) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *Activity) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Activity) GetProvider() Activity_Provider {
	if x != nil {
		return x.Provider
	}
	return Activity_PROVIDER_UNSPECIFIED
}

func (x *Activity) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Activity) GetCandidateTokens() int32 {
	if x != nil {
		return x.CandidateTokens
	}
	return 0
}

func (x *Activity) GetCachedTokens() int32 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *Activity) GetCacheWriteTokens() int32 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *Activity) GetReasoningTokens() int32 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *Activity) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Activity) GetEstimatedCostMicros() int64 {
	if x != nil {
		return x.EstimatedCostMicros
	}
	return 0
}

func (x *Activity) GetBilledCostMicros() int64 {
	if x != nil {
		return x.BilledCostMicros
	}
	return 0
}

func (x *Activity) GetRateCardVersion() string {
	if x != nil {
		return x.RateCardVersion
	}
	return ""
}

func (x *Activity) GetCharges() []*Charge {
	if x != nil {
		return x.Charges
	}
	return nil
}

func (x *Activity) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Activity) GetStatus() Activity_Status {
	if x != nil {
		return x.Status
	}
	return Activity_STATUS_UNSPECIFIED
}

func (x *Activity) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Activity) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Activity) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *Activity) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Activity) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Activity) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// A charge that is not measured in tokens.
type Charge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The priceable unit being charged for.
	// Format: `priceableUnits/{priceable_unit}`
	PriceableUnit string `protobuf:"bytes,1,opt,name=priceable_unit,json=priceableUnit,proto3" json:"priceable_unit,omitempty"`
	// How many of the unit were consumed, e.g. `3` web searches.
	Quantity int64 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// What this charge is expected to cost, in millionths of a US dollar.
	// Computed by the server from the rate card.
	EstimatedCostMicros int64 `protobuf:"varint,3,opt,name=estimated_cost_micros,json=estimatedCostMicros,proto3" json:"estimated_cost_micros,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Charge) Reset() {
	*x = Charge{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Charge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Charge) ProtoMessage() {}

func (x *Charge) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Charge.ProtoReflect.Descriptor instead.
func (*Charge) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{1}
}

func (x *Charge) GetPriceableUnit() string {
	if x != nil {
		return x.PriceableUnit
	}
	return ""
}

func (x *Charge) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Charge) GetEstimatedCostMicros() int64 {
	if x != nil {
		return x.EstimatedCostMicros
	}
	return 0
}

// Request for [ActivitiesService.CreateActivity].
type CreateActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation the activity belongs to.
	// Format: `organisations/{organisation}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The activity to record. Its `name` is assigned by the server.
	Activity *Activity `protobuf:"bytes,2,opt,name=activity,proto3" json:"activity,omitempty"`
	// Optional caller-supplied identifier that makes the write idempotent.
	//
	// A recorder that retries after a timeout sends the same value, and the
	// server returns the activity it already wrote rather than double counting.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{2}
}

func (x *CreateActivityRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateActivityRequest) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *CreateActivityRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Request for [ActivitiesService.BatchCreateActivities].
type BatchCreateActivitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace the activities belong to.
	// Format: `organisations/{organisation}/workspaces/{workspace}`
	//
	// An `organisations/{organisation}` on its own is accepted and files the batch under that organisation's default workspace, which is what a recorder written before workspaces existed sends and must keep being able to send.
	//
	// One batch, one workspace. A caller recording for several sends one batch each, because the batch is rejected or accepted as a whole and a single parent is what keeps a record's tenant out of the reach of the record itself.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The activities to record. Rejected as a whole if any one is invalid.
	Activities []*Activity `protobuf:"bytes,2,rep,name=activities,proto3" json:"activities,omitempty"`
	// Optional caller-supplied identifier that makes the batch idempotent.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateActivitiesRequest) Reset() {
	*x = BatchCreateActivitiesRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateActivitiesRequest) ProtoMessage() {}

func (x *BatchCreateActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateActivitiesRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCreateActivitiesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchCreateActivitiesRequest) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *BatchCreateActivitiesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Response for [ActivitiesService.BatchCreateActivities].
type BatchCreateActivitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The activities that were recorded, in the order they were supplied.
	Activities    []*Activity `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateActivitiesResponse) Reset() {
	*x = BatchCreateActivitiesResponse{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateActivitiesResponse) ProtoMessage() {}

func (x *BatchCreateActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateActivitiesResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

// Request for [ActivitiesService.GetActivity].
type GetActivityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the activity to retrieve.
	// Format: `organisations/{organisation}/workspaces/{workspace}/activities/{activity}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityRequest) Reset() {
	*x = GetActivityRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityRequest) ProtoMessage() {}

func (x *GetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityRequest.ProtoReflect.Descriptor instead.
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{5}
}

func (x *GetActivityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request for [ActivitiesService.ListActivities].
type ListActivitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation, or the one workspace within it, whose activities to list.
	// Format: `organisations/{organisation}` or `organisations/{organisation}/workspaces/{workspace}`
	//
	// An organisation reads every workspace under it; a workspace reads only its own. This is the whole of the access decision, and it is why the two are a different `parent` rather than the same read with a filter term.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Maximum activities to return. Defaults to `100`, capped at `1000`.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token from a previous response, to retrieve the next page.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filter, confining the page to activities matching every term.
	//
	// A filter is one or more terms joined by `AND`, each `field = value`, e.g. `agent = "organisations/acme/agents/atlas" AND status = FAILED`. A value may be quoted; it must be when it holds a space. The fields are the ones activities can be grouped by: `workspace`, `project`, `agent`, `model`, `provider`, `user`, `caller_service`, `caller_component`, `skill`, `status`, `error_code` and `kind`. Only equality is served, and only `AND`; the window is `start_time` and `end_time`, not a term. An unknown field or any other operator is refused rather than ignored.
	//
	// Cannot widen the organisation: scope always comes from `parent`, and a term naming an agent outside it matches nothing.
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional sort order. The one order served is `occurred_at desc`, which is also the default, so a page is the most recent work first.
	OrderBy string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Start of the window to list, inclusive. With `end_time`, confines the page to when the work happened; without either, every activity under `parent` is listed.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End of the window to list, exclusive.
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesRequest) Reset() {
	*x = ListActivitiesRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesRequest) ProtoMessage() {}

func (x *ListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{6}
}

func (x *ListActivitiesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListActivitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListActivitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListActivitiesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListActivitiesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListActivitiesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListActivitiesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// Response for [ActivitiesService.ListActivities].
type ListActivitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The activities in this page.
	Activities []*Activity `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	// Token to retrieve the next page, empty when there are no more.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesResponse) Reset() {
	*x = ListActivitiesResponse{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesResponse) ProtoMessage() {}

func (x *ListActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ListActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{7}
}

func (x *ListActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ListActivitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request for [ActivitiesService.StreamListActivities].
type StreamListActivitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation, or the one workspace within it, whose activities to stream.
	// Format: `organisations/{organisation}` or `organisations/{organisation}/workspaces/{workspace}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional filter, with the same syntax as
	// [ListActivitiesRequest.filter].
	Filter        string `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamListActivitiesRequest) Reset() {
	*x = StreamListActivitiesRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamListActivitiesRequest) ProtoMessage() {}

func (x *StreamListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*StreamListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{8}
}

func (x *StreamListActivitiesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *StreamListActivitiesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Request for [ActivitiesService.AggregateActivities].
type AggregateActivitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation, or the one workspace within it, whose spend to aggregate.
	// Format: `organisations/{organisation}` or `organisations/{organisation}/workspaces/{workspace}`
	//
	// An organisation aggregates across every workspace under it, which grouped by `workspace` is one row per tenant. A workspace aggregates only its own.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Dimensions to group by, e.g. `["agent", "model"]`.
	//
	// Valid dimensions are `workspace`, `project`, `agent`, `model`, `provider`, `user`,
	// `caller_service`, `caller_component`, `skill`, `status`, `error_code`, `kind`, `date` and `hour`. `kind` is `model`, `tool` or `call`: a tool call is one recorded under a `tool:` component, a model call one that names a model or counted tokens, and a call is anything else. `date` and `hour` are UTC. Grouping by `workspace` under an organisation is one row per tenant; under a single workspace it is one row. An empty list returns a single total for whatever `parent` named.
	GroupBy []string `protobuf:"bytes,2,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	// Optional filter, with the same terms as [ListActivitiesRequest.filter], so a panel asks for exactly the rows it draws: `user = "8c21e0b4"` grouped by `date` is one person's spend by day, without the rest of the organisation's rows being read and discarded. Cannot widen the organisation. `agent` below is the same as a filter term on `agent`, kept for callers that only ever confine to one.
	Filter string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	// Start of the window to aggregate, inclusive.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End of the window to aggregate, exclusive.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Maximum rows to return. Defaults to `100`, capped at `1000`.
	//
	// Grouping by several dimensions at once can produce a great many rows, so
	// this method paginates like a list rather than returning everything.
	PageSize int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token from a previous response, to retrieve the next page.
	PageToken string `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Confines the aggregate to one agent's activities.
	// Format: `organisations/{organisation}/agents/{agent}`; must sit under
	// `parent`.
	Agent         string `protobuf:"bytes,8,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateActivitiesRequest) Reset() {
	*x = AggregateActivitiesRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateActivitiesRequest) ProtoMessage() {}

func (x *AggregateActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateActivitiesRequest.ProtoReflect.Descriptor instead.
func (*AggregateActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{9}
}

func (x *AggregateActivitiesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *AggregateActivitiesRequest) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *AggregateActivitiesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *AggregateActivitiesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AggregateActivitiesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *AggregateActivitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AggregateActivitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *AggregateActivitiesRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

// Response for [ActivitiesService.AggregateActivities].
type AggregateActivitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One row per combination of the requested dimensions.
	Rows []*AggregateRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// Token to retrieve the next page, empty when there are no more.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateActivitiesResponse) Reset() {
	*x = AggregateActivitiesResponse{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateActivitiesResponse) ProtoMessage() {}

func (x *AggregateActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateActivitiesResponse.ProtoReflect.Descriptor instead.
func (*AggregateActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{10}
}

func (x *AggregateActivitiesResponse) GetRows() []*AggregateRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *AggregateActivitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Spend for one combination of grouping dimensions.
type AggregateRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dimension values for this row, keyed by dimension name, e.g.
	// `{"agent": "organisations/acme/agents/atlas", "model": "gemini-2.5-pro"}`.
	Dimensions map[string]string `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Sum of `estimated_cost_micros` over the matching activities.
	EstimatedCostMicros int64 `protobuf:"varint,2,opt,name=estimated_cost_micros,json=estimatedCostMicros,proto3" json:"estimated_cost_micros,omitempty"`
	// Sum of `billed_cost_micros` over the matching activities. Lower than the
	// estimate where reconciliation has not yet run for part of the window.
	BilledCostMicros int64 `protobuf:"varint,3,opt,name=billed_cost_micros,json=billedCostMicros,proto3" json:"billed_cost_micros,omitempty"`
	// Sum of `total_tokens` over the matching activities.
	TotalTokens int64 `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	// How many activities the row covers.
	ActivityCount int64 `protobuf:"varint,5,opt,name=activity_count,json=activityCount,proto3" json:"activity_count,omitempty"`
	// Sums of each kind of token, kept apart because each is priced at its own rate and a total cannot be taken back apart once summed.
	PromptTokens     int64 `protobuf:"varint,6,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CandidateTokens  int64 `protobuf:"varint,7,opt,name=candidate_tokens,json=candidateTokens,proto3" json:"candidate_tokens,omitempty"`
	CachedTokens     int64 `protobuf:"varint,8,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	CacheWriteTokens int64 `protobuf:"varint,9,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	ReasoningTokens  int64 `protobuf:"varint,10,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	// How many of the activities failed or were denied: neither produced the work the call was made for.
	FailedCount int64 `protobuf:"varint,11,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	// How many hit a limit and did partial work.
	TruncatedCount int64 `protobuf:"varint,12,opt,name=truncated_count,json=truncatedCount,proto3" json:"truncated_count,omitempty"`
	// How many model calls used tokens and were priced at nothing, which is what a call looks like when the rate card could not match its model.
	UnpricedCount int64 `protobuf:"varint,13,opt,name=unpriced_count,json=unpricedCount,proto3" json:"unpriced_count,omitempty"`
	// How many of the activities were model calls, and how many tool calls, by the same rule as the `kind` dimension. The two do not have to sum to `activity_count`: a call that names no model, counted no tokens and ran no tool is neither.
	//
	// A tool call carries no model, so a row grouped by `model` holds the tool calls under an empty value rather than leaving them out.
	ModelCalls int64 `protobuf:"varint,14,opt,name=model_calls,json=modelCalls,proto3" json:"model_calls,omitempty"`
	ToolCalls  int64 `protobuf:"varint,15,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// How many distinct requests and people the activities belong to. Exact for the window asked for, and not additive across windows: a person active on two days is one person in a two-day window.
	DistinctRequests int64 `protobuf:"varint,16,opt,name=distinct_requests,json=distinctRequests,proto3" json:"distinct_requests,omitempty"`
	DistinctUsers    int64 `protobuf:"varint,17,opt,name=distinct_users,json=distinctUsers,proto3" json:"distinct_users,omitempty"`
	// Duration at the 50th and 95th percentile, in milliseconds, over the activities that reported one. Approximate, and not additive across windows.
	P50DurationMs int64 `protobuf:"varint,18,opt,name=p50_duration_ms,json=p50DurationMs,proto3" json:"p50_duration_ms,omitempty"`
	P95DurationMs int64 `protobuf:"varint,19,opt,name=p95_duration_ms,json=p95DurationMs,proto3" json:"p95_duration_ms,omitempty"`
	// When the earliest and latest of the activities happened.
	FirstOccurredAt *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=first_occurred_at,json=firstOccurredAt,proto3" json:"first_occurred_at,omitempty"`
	LastOccurredAt  *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=last_occurred_at,json=lastOccurredAt,proto3" json:"last_occurred_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AggregateRow) Reset() {
	*x = AggregateRow{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRow) ProtoMessage() {}

func (x *AggregateRow) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRow.ProtoReflect.Descriptor instead.
func (*AggregateRow) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{11}
}

func (x *AggregateRow) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *AggregateRow) GetEstimatedCostMicros() int64 {
	if x != nil {
		return x.EstimatedCostMicros
	}
	return 0
}

func (x *AggregateRow) GetBilledCostMicros() int64 {
	if x != nil {
		return x.BilledCostMicros
	}
	return 0
}

func (x *AggregateRow) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *AggregateRow) GetActivityCount() int64 {
	if x != nil {
		return x.ActivityCount
	}
	return 0
}

func (x *AggregateRow) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *AggregateRow) GetCandidateTokens() int64 {
	if x != nil {
		return x.CandidateTokens
	}
	return 0
}

func (x *AggregateRow) GetCachedTokens() int64 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *AggregateRow) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *AggregateRow) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *AggregateRow) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *AggregateRow) GetTruncatedCount() int64 {
	if x != nil {
		return x.TruncatedCount
	}
	return 0
}

func (x *AggregateRow) GetUnpricedCount() int64 {
	if x != nil {
		return x.UnpricedCount
	}
	return 0
}

func (x *AggregateRow) GetModelCalls() int64 {
	if x != nil {
		return x.ModelCalls
	}
	return 0
}

func (x *AggregateRow) GetToolCalls() int64 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *AggregateRow) GetDistinctRequests() int64 {
	if x != nil {
		return x.DistinctRequests
	}
	return 0
}

func (x *AggregateRow) GetDistinctUsers() int64 {
	if x != nil {
		return x.DistinctUsers
	}
	return 0
}

func (x *AggregateRow) GetP50DurationMs() int64 {
	if x != nil {
		return x.P50DurationMs
	}
	return 0
}

func (x *AggregateRow) GetP95DurationMs() int64 {
	if x != nil {
		return x.P95DurationMs
	}
	return 0
}

func (x *AggregateRow) GetFirstOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstOccurredAt
	}
	return nil
}

func (x *AggregateRow) GetLastOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastOccurredAt
	}
	return nil
}

var File_techbridge_ap_metering_v1_activity_proto protoreflect.FileDescriptor

const file_techbridge_ap_metering_v1_activity_proto_rawDesc = "" +
	"\n" +
	"(techbridge/ap/metering/v1/activity.proto\x12\x19techbridge.ap.metering.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\v\n" +
	"\bActivity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\x05agent\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05agent\x12\x1e\n" +
	"\arequest\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\arequest\x12\x18\n" +
	"\asession\x18\x04 \x01(\tR\asession\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12%\n" +
	"\x0ecaller_service\x18\x06 \x01(\tR\rcallerService\x12)\n" +
	"\x10caller_component\x18\a \x01(\tR\x0fcallerComponent\x12\x14\n" +
	"\x05skill\x18\b \x01(\tR\x05skill\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12H\n" +
	"\bprovider\x18\n" +
	" \x01(\x0e2,.techbridge.ap.metering.v1.Activity.ProviderR\bprovider\x12#\n" +
	"\rprompt_tokens\x18\v \x01(\x05R\fpromptTokens\x12)\n" +
	"\x10candidate_tokens\x18\f \x01(\x05R\x0fcandidateTokens\x12#\n" +
	"\rcached_tokens\x18\r \x01(\x05R\fcachedTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x0e \x01(\x05R\x10cacheWriteTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x0f \x01(\x05R\x0freasoningTokens\x12!\n" +
	"\ftotal_tokens\x18\x10 \x01(\x05R\vtotalTokens\x128\n" +
	"\x15estimated_cost_micros\x18\x11 \x01(\x03B\x04\xe2A\x01\x03R\x13estimatedCostMicros\x122\n" +
	"\x12billed_cost_micros\x18\x12 \x01(\x03B\x04\xe2A\x01\x03R\x10billedCostMicros\x120\n" +
	"\x11rate_card_version\x18\x13 \x01(\tB\x04\xe2A\x01\x03R\x0frateCardVersion\x12;\n" +
	"\acharges\x18\x14 \x03(\v2!.techbridge.ap.metering.v1.ChargeR\acharges\x12\x1f\n" +
	"\vduration_ms\x18\x15 \x01(\x03R\n" +
	"durationMs\x12B\n" +
	"\x06status\x18\x16 \x01(\x0e2*.techbridge.ap.metering.v1.Activity.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x17 \x01(\tR\terrorCode\x12\x18\n" +
	"\aproject\x18\x19 \x01(\tR\aproject\x12;\n" +
	"\voccurred_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x18\n" +
	"\x04etag\x18a \x01(\tB\x04\xe2A\x01\x03R\x04etag\x12A\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime\"^\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tVERTEX_AI\x10\x01\x12\r\n" +
	"\tANTHROPIC\x10\x02\x12\n" +
	"\n" +
	"\x06OPENAI\x10\x03\x12\x0e\n" +
	"\n" +
	"PERPLEXITY\x10\x04\"O\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\n" +
	"\n" +
	"\x06DENIED\x10\x03\x12\r\n" +
	"\tTRUNCATED\x10\x04:o\xeaAl\n" +
	"\x1fmetering.ap.techbridge/Activity\x12Iorganisations/{organisation}/workspaces/{workspace}/activities/{activity}\"\x91\x01\n" +
	"\x06Charge\x12+\n" +
	"\x0epriceable_unit\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\rpriceableUnit\x12 \n" +
	"\bquantity\x18\x02 \x01(\x03B\x04\xe2A\x01\x02R\bquantity\x128\n" +
	"\x15estimated_cost_micros\x18\x03 \x01(\x03B\x04\xe2A\x01\x03R\x13estimatedCostMicros\"\x9b\x01\n" +
	"\x15CreateActivityRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12E\n" +
	"\bactivity\x18\x02 \x01(\v2#.techbridge.ap.metering.v1.ActivityB\x04\xe2A\x01\x02R\bactivity\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\xa6\x01\n" +
	"\x1cBatchCreateActivitiesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12I\n" +
	"\n" +
	"activities\x18\x02 \x03(\v2#.techbridge.ap.metering.v1.ActivityB\x04\xe2A\x01\x02R\n" +
	"activities\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"d\n" +
	"\x1dBatchCreateActivitiesResponse\x12C\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2#.techbridge.ap.metering.v1.ActivityR\n" +
	"activities\".\n" +
	"\x12GetActivityRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\"\x96\x02\n" +
	"\x15ListActivitiesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x85\x01\n" +
	"\x16ListActivitiesResponse\x12C\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2#.techbridge.ap.metering.v1.ActivityR\n" +
	"activities\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"S\n" +
	"\x1bStreamListActivitiesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\"\xbd\x02\n" +
	"\x1aAggregateActivitiesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x19\n" +
	"\bgroup_by\x18\x02 \x03(\tR\agroupBy\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12?\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x02R\tstartTime\x12;\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x02R\aendTime\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\x12\x14\n" +
	"\x05agent\x18\b \x01(\tR\x05agent\"\x82\x01\n" +
	"\x1bAggregateActivitiesResponse\x12;\n" +
	"\x04rows\x18\x01 \x03(\v2'.techbridge.ap.metering.v1.AggregateRowR\x04rows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x85\b\n" +
	"\fAggregateRow\x12W\n" +
	"\n" +
	"dimensions\x18\x01 \x03(\v27.techbridge.ap.metering.v1.AggregateRow.DimensionsEntryR\n" +
	"dimensions\x122\n" +
	"\x15estimated_cost_micros\x18\x02 \x01(\x03R\x13estimatedCostMicros\x12,\n" +
	"\x12billed_cost_micros\x18\x03 \x01(\x03R\x10billedCostMicros\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x03R\vtotalTokens\x12%\n" +
	"\x0eactivity_count\x18\x05 \x01(\x03R\ractivityCount\x12#\n" +
	"\rprompt_tokens\x18\x06 \x01(\x03R\fpromptTokens\x12)\n" +
	"\x10candidate_tokens\x18\a \x01(\x03R\x0fcandidateTokens\x12#\n" +
	"\rcached_tokens\x18\b \x01(\x03R\fcachedTokens\x12,\n" +
	"\x12cache_write_tokens\x18\t \x01(\x03R\x10cacheWriteTokens\x12)\n" +
	"\x10reasoning_tokens\x18\n" +
	" \x01(\x03R\x0freasoningTokens\x12!\n" +
	"\ffailed_count\x18\v \x01(\x03R\vfailedCount\x12'\n" +
	"\x0ftruncated_count\x18\f \x01(\x03R\x0etruncatedCount\x12%\n" +
	"\x0eunpriced_count\x18\r \x01(\x03R\runpricedCount\x12\x1f\n" +
	"\vmodel_calls\x18\x0e \x01(\x03R\n" +
	"modelCalls\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\x0f \x01(\x03R\ttoolCalls\x12+\n" +
	"\x11distinct_requests\x18\x10 \x01(\x03R\x10distinctRequests\x12%\n" +
	"\x0edistinct_users\x18\x11 \x01(\x03R\rdistinctUsers\x12&\n" +
	"\x0fp50_duration_ms\x18\x12 \x01(\x03R\rp50DurationMs\x12&\n" +
	"\x0fp95_duration_ms\x18\x13 \x01(\x03R\rp95DurationMs\x12F\n" +
	"\x11first_occurred_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\x0ffirstOccurredAt\x12D\n" +
	"\x10last_occurred_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastOccurredAt\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd0\a\n" +
	"\x11ActivitiesService\x12i\n" +
	"\x0eCreateActivity\x120.techbridge.ap.metering.v1.CreateActivityRequest\x1a#.techbridge.ap.metering.v1.Activity\"\x00\x12\x8c\x01\n" +
	"\x15BatchCreateActivities\x127.techbridge.ap.metering.v1.BatchCreateActivitiesRequest\x1a8.techbridge.ap.metering.v1.BatchCreateActivitiesResponse\"\x00\x12c\n" +
	"\vGetActivity\x12-.techbridge.ap.metering.v1.GetActivityRequest\x1a#.techbridge.ap.metering.v1.Activity\"\x00\x12\xde\x01\n" +
	"\x0eListActivities\x120.techbridge.ap.metering.v1.ListActivitiesRequest\x1a1.techbridge.ap.metering.v1.ListActivitiesResponse\"g\x82\xd3\xe4\x93\x02aZ6\x124/v1/{parent=organisations/*/workspaces/*}/activities\x12'/v1/{parent=organisations/*}/activities\x12\x81\x02\n" +
	"\x13AggregateActivities\x125.techbridge.ap.metering.v1.AggregateActivitiesRequest\x1a6.techbridge.ap.metering.v1.AggregateActivitiesResponse\"{\x82\xd3\xe4\x93\x02uZ@\x12>/v1/{parent=organisations/*/workspaces/*}/activities:aggregate\x121/v1/{parent=organisations/*}/activities:aggregate\x12w\n" +
	"\x14StreamListActivities\x126.techbridge.ap.metering.v1.StreamListActivitiesRequest\x1a#.techbridge.ap.metering.v1.Activity\"\x000\x01B#Z!alis.build/techbridge/ap/meteringb\x06proto3"

var (
	file_techbridge_ap_metering_v1_activity_proto_rawDescOnce sync.Once
	file_techbridge_ap_metering_v1_activity_proto_rawDescData []byte
)

func file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP() []byte {
	file_techbridge_ap_metering_v1_activity_proto_rawDescOnce.Do(func() {
		file_techbridge_ap_metering_v1_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_activity_proto_rawDesc), len(file_techbridge_ap_metering_v1_activity_proto_rawDesc)))
	})
	return file_techbridge_ap_metering_v1_activity_proto_rawDescData
}

var file_techbridge_ap_metering_v1_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_techbridge_ap_metering_v1_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_techbridge_ap_metering_v1_activity_proto_goTypes = []any{
	(Activity_Provider)(0),                // 0: techbridge.ap.metering.v1.Activity.Provider
	(Activity_Status)(0),                  // 1: techbridge.ap.metering.v1.Activity.Status
	(*Activity)(nil),                      // 2: techbridge.ap.metering.v1.Activity
	(*Charge)(nil),                        // 3: techbridge.ap.metering.v1.Charge
	(*CreateActivityRequest)(nil),         // 4: techbridge.ap.metering.v1.CreateActivityRequest
	(*BatchCreateActivitiesRequest)(nil),  // 5: techbridge.ap.metering.v1.BatchCreateActivitiesRequest
	(*BatchCreateActivitiesResponse)(nil), // 6: techbridge.ap.metering.v1.BatchCreateActivitiesResponse
	(*GetActivityRequest)(nil),            // 7: techbridge.ap.metering.v1.GetActivityRequest
	(*ListActivitiesRequest)(nil),         // 8: techbridge.ap.metering.v1.ListActivitiesRequest
	(*ListActivitiesResponse)(nil),        // 9: techbridge.ap.metering.v1.ListActivitiesResponse
	(*StreamListActivitiesRequest)(nil),   // 10: techbridge.ap.metering.v1.StreamListActivitiesRequest
	(*AggregateActivitiesRequest)(nil),    // 11: techbridge.ap.metering.v1.AggregateActivitiesRequest
	(*AggregateActivitiesResponse)(nil),   // 12: techbridge.ap.metering.v1.AggregateActivitiesResponse
	(*AggregateRow)(nil),                  // 13: techbridge.ap.metering.v1.AggregateRow
	nil,                                   // 14: techbridge.ap.metering.v1.AggregateRow.DimensionsEntry
	(*timestamppb.Timestamp)(nil),         // 15: google.protobuf.Timestamp
}
var file_techbridge_ap_metering_v1_activity_proto_depIdxs = []int32{
	0,  // 0: techbridge.ap.metering.v1.Activity.provider:type_name -> techbridge.ap.metering.v1.Activity.Provider
	3,  // 1: techbridge.ap.metering.v1.Activity.charges:type_name -> techbridge.ap.metering.v1.Charge
	1,  // 2: techbridge.ap.metering.v1.Activity.status:type_name -> techbridge.ap.metering.v1.Activity.Status
	15, // 3: techbridge.ap.metering.v1.Activity.occurred_at:type_name -> google.protobuf.Timestamp
	15, // 4: techbridge.ap.metering.v1.Activity.create_time:type_name -> google.protobuf.Timestamp
	15, // 5: techbridge.ap.metering.v1.Activity.update_time:type_name -> google.protobuf.Timestamp
	2,  // 6: techbridge.ap.metering.v1.CreateActivityRequest.activity:type_name -> techbridge.ap.metering.v1.Activity
	2,  // 7: techbridge.ap.metering.v1.BatchCreateActivitiesRequest.activities:type_name -> techbridge.ap.metering.v1.Activity
	2,  // 8: techbridge.ap.metering.v1.BatchCreateActivitiesResponse.activities:type_name -> techbridge.ap.metering.v1.Activity
	15, // 9: techbridge.ap.metering.v1.ListActivitiesRequest.start_time:type_name -> google.protobuf.Timestamp
	15, // 10: techbridge.ap.metering.v1.ListActivitiesRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 11: techbridge.ap.metering.v1.ListActivitiesResponse.activities:type_name -> techbridge.ap.metering.v1.Activity
	15, // 12: techbridge.ap.metering.v1.AggregateActivitiesRequest.start_time:type_name -> google.protobuf.Timestamp
	15, // 13: techbridge.ap.metering.v1.AggregateActivitiesRequest.end_time:type_name -> google.protobuf.Timestamp
	13, // 14: techbridge.ap.metering.v1.AggregateActivitiesResponse.rows:type_name -> techbridge.ap.metering.v1.AggregateRow
	14, // 15: techbridge.ap.metering.v1.AggregateRow.dimensions:type_name -> techbridge.ap.metering.v1.AggregateRow.DimensionsEntry
	15, // 16: techbridge.ap.metering.v1.AggregateRow.first_occurred_at:type_name -> google.protobuf.Timestamp
	15, // 17: techbridge.ap.metering.v1.AggregateRow.last_occurred_at:type_name -> google.protobuf.Timestamp
	4,  // 18: techbridge.ap.metering.v1.ActivitiesService.CreateActivity:input_type -> techbridge.ap.metering.v1.CreateActivityRequest
	5,  // 19: techbridge.ap.metering.v1.ActivitiesService.BatchCreateActivities:input_type -> techbridge.ap.metering.v1.BatchCreateActivitiesRequest
	7,  // 20: techbridge.ap.metering.v1.ActivitiesService.GetActivity:input_type -> techbridge.ap.metering.v1.GetActivityRequest
	8,  // 21: techbridge.ap.metering.v1.ActivitiesService.ListActivities:input_type -> techbridge.ap.metering.v1.ListActivitiesRequest
	11, // 22: techbridge.ap.metering.v1.ActivitiesService.AggregateActivities:input_type -> techbridge.ap.metering.v1.AggregateActivitiesRequest
	10, // 23: techbridge.ap.metering.v1.ActivitiesService.StreamListActivities:input_type -> techbridge.ap.metering.v1.StreamListActivitiesRequest
	2,  // 24: techbridge.ap.metering.v1.ActivitiesService.CreateActivity:output_type -> techbridge.ap.metering.v1.Activity
	6,  // 25: techbridge.ap.metering.v1.ActivitiesService.BatchCreateActivities:output_type -> techbridge.ap.metering.v1.BatchCreateActivitiesResponse
	2,  // 26: techbridge.ap.metering.v1.ActivitiesService.GetActivity:output_type -> techbridge.ap.metering.v1.Activity
	9,  // 27: techbridge.ap.metering.v1.ActivitiesService.ListActivities:output_type -> techbridge.ap.metering.v1.ListActivitiesResponse
	12, // 28: techbridge.ap.metering.v1.ActivitiesService.AggregateActivities:output_type -> techbridge.ap.metering.v1.AggregateActivitiesResponse
	2,  // 29: techbridge.ap.metering.v1.ActivitiesService.StreamListActivities:output_type -> techbridge.ap.metering.v1.Activity
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_techbridge_ap_metering_v1_activity_proto_init() }
func file_techbridge_ap_metering_v1_activity_proto_init() {
	if File_techbridge_ap_metering_v1_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_activity_proto_rawDesc), len(file_techbridge_ap_metering_v1_activity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techbridge_ap_metering_v1_activity_proto_goTypes,
		DependencyIndexes: file_techbridge_ap_metering_v1_activity_proto_depIdxs,
		EnumInfos:         file_techbridge_ap_metering_v1_activity_proto_enumTypes,
		MessageInfos:      file_techbridge_ap_metering_v1_activity_proto_msgTypes,
	}.Build()
	File_techbridge_ap_metering_v1_activity_proto = out.File
	file_techbridge_ap_metering_v1_activity_proto_goTypes = nil
	file_techbridge_ap_metering_v1_activity_proto_depIdxs = nil
}
