// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: techbridge/ap/metering/v1/activity.proto

package metering

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivitiesService_CreateActivity_FullMethodName        = "/techbridge.ap.metering.v1.ActivitiesService/CreateActivity"
	ActivitiesService_BatchCreateActivities_FullMethodName = "/techbridge.ap.metering.v1.ActivitiesService/BatchCreateActivities"
	ActivitiesService_GetActivity_FullMethodName           = "/techbridge.ap.metering.v1.ActivitiesService/GetActivity"
	ActivitiesService_ListActivities_FullMethodName        = "/techbridge.ap.metering.v1.ActivitiesService/ListActivities"
	ActivitiesService_AggregateActivities_FullMethodName   = "/techbridge.ap.metering.v1.ActivitiesService/AggregateActivities"
	ActivitiesService_StreamListActivities_FullMethodName  = "/techbridge.ap.metering.v1.ActivitiesService/StreamListActivities"
)

// ActivitiesServiceClient is the client API for ActivitiesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivitiesServiceClient interface {
	CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*Activity, error)
	BatchCreateActivities(ctx context.Context, in *BatchCreateActivitiesRequest, opts ...grpc.CallOption) (*BatchCreateActivitiesResponse, error)
	GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*Activity, error)
	ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
	AggregateActivities(ctx context.Context, in *AggregateActivitiesRequest, opts ...grpc.CallOption) (*AggregateActivitiesResponse, error)
	StreamListActivities(ctx context.Context, in *StreamListActivitiesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Activity], error)
}

type activitiesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivitiesServiceClient(cc grpc.ClientConnInterface) ActivitiesServiceClient {
	return &activitiesServiceClient{cc}
}

func (c *activitiesServiceClient) CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*Activity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Activity)
	err := c.cc.Invoke(ctx, ActivitiesService_CreateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesServiceClient) BatchCreateActivities(ctx context.Context, in *BatchCreateActivitiesRequest, opts ...grpc.CallOption) (*BatchCreateActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateActivitiesResponse)
	err := c.cc.Invoke(ctx, ActivitiesService_BatchCreateActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesServiceClient) GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*Activity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Activity)
	err := c.cc.Invoke(ctx, ActivitiesService_GetActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesServiceClient) ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, ActivitiesService_ListActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesServiceClient) AggregateActivities(ctx context.Context, in *AggregateActivitiesRequest, opts ...grpc.CallOption) (*AggregateActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateActivitiesResponse)
	err := c.cc.Invoke(ctx, ActivitiesService_AggregateActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitiesServiceClient) StreamListActivities(ctx context.Context, in *StreamListActivitiesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Activity], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ActivitiesService_ServiceDesc.Streams[0], ActivitiesService_StreamListActivities_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamListActivitiesRequest, Activity]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActivitiesService_StreamListActivitiesClient = grpc.ServerStreamingClient[Activity]

// ActivitiesServiceServer is the server API for ActivitiesService service.
// All implementations must embed UnimplementedActivitiesServiceServer
// for forward compatibility.
type ActivitiesServiceServer interface {
	CreateActivity(context.Context, *CreateActivityRequest) (*Activity, error)
	BatchCreateActivities(context.Context, *BatchCreateActivitiesRequest) (*BatchCreateActivitiesResponse, error)
	GetActivity(context.Context, *GetActivityRequest) (*Activity, error)
	ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error)
	AggregateActivities(context.Context, *AggregateActivitiesRequest) (*AggregateActivitiesResponse, error)
	StreamListActivities(*StreamListActivitiesRequest, grpc.ServerStreamingServer[Activity]) error
	mustEmbedUnimplementedActivitiesServiceServer()
}

// UnimplementedActivitiesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivitiesServiceServer struct{}

func (UnimplementedActivitiesServiceServer) CreateActivity(context.Context, *CreateActivityRequest) (*Activity, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedActivitiesServiceServer) BatchCreateActivities(context.Context, *BatchCreateActivitiesRequest) (*BatchCreateActivitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateActivities not implemented")
}
func (UnimplementedActivitiesServiceServer) GetActivity(context.Context, *GetActivityRequest) (*Activity, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedActivitiesServiceServer) ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActivities not implemented")
}
func (UnimplementedActivitiesServiceServer) AggregateActivities(context.Context, *AggregateActivitiesRequest) (*AggregateActivitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AggregateActivities not implemented")
}
func (UnimplementedActivitiesServiceServer) StreamListActivities(*StreamListActivitiesRequest, grpc.ServerStreamingServer[Activity]) error {
	return status.Error(codes.Unimplemented, "method StreamListActivities not implemented")
}
func (UnimplementedActivitiesServiceServer) mustEmbedUnimplementedActivitiesServiceServer() {}
func (UnimplementedActivitiesServiceServer) testEmbeddedByValue()                           {}

// UnsafeActivitiesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivitiesServiceServer will
// result in compilation errors.
type UnsafeActivitiesServiceServer interface {
	mustEmbedUnimplementedActivitiesServiceServer()
}

func RegisterActivitiesServiceServer(s grpc.ServiceRegistrar, srv ActivitiesServiceServer) {
	// If the following call panics, it indicates UnimplementedActivitiesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivitiesService_ServiceDesc, srv)
}

func _ActivitiesService_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivitiesService_CreateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).CreateActivity(ctx, req.(*CreateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitiesService_BatchCreateActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).BatchCreateActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivitiesService_BatchCreateActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).BatchCreateActivities(ctx, req.(*BatchCreateActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitiesService_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivitiesService_GetActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).GetActivity(ctx, req.(*GetActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitiesService_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivitiesService_ListActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).ListActivities(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitiesService_AggregateActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivitiesServiceServer).AggregateActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivitiesService_AggregateActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivitiesServiceServer).AggregateActivities(ctx, req.(*AggregateActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivitiesService_StreamListActivities_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamListActivitiesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ActivitiesServiceServer).StreamListActivities(m, &grpc.GenericServerStream[StreamListActivitiesRequest, Activity]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActivitiesService_StreamListActivitiesServer = grpc.ServerStreamingServer[Activity]

// ActivitiesService_ServiceDesc is the grpc.ServiceDesc for ActivitiesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivitiesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "techbridge.ap.metering.v1.ActivitiesService",
	HandlerType: (*ActivitiesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateActivity",
			Handler:    _ActivitiesService_CreateActivity_Handler,
		},
		{
			MethodName: "BatchCreateActivities",
			Handler:    _ActivitiesService_BatchCreateActivities_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _ActivitiesService_GetActivity_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _ActivitiesService_ListActivities_Handler,
		},
		{
			MethodName: "AggregateActivities",
			Handler:    _ActivitiesService_AggregateActivities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamListActivities",
			Handler:       _ActivitiesService_StreamListActivities_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "techbridge/ap/metering/v1/activity.proto",
}
