// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: techbridge/ap/metering/v1/activity.proto

package metering

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Activity_Provider int32

const (
	Activity_PROVIDER_UNSPECIFIED Activity_Provider = 0
	Activity_VERTEX_AI            Activity_Provider = 1
	Activity_ANTHROPIC            Activity_Provider = 2
	Activity_OPENAI               Activity_Provider = 3
	Activity_PERPLEXITY           Activity_Provider = 4
)

// Enum value maps for Activity_Provider.
var (
	Activity_Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "VERTEX_AI",
		2: "ANTHROPIC",
		3: "OPENAI",
		4: "PERPLEXITY",
	}
	Activity_Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"VERTEX_AI":            1,
		"ANTHROPIC":            2,
		"OPENAI":               3,
		"PERPLEXITY":           4,
	}
)

func (x Activity_Provider) Enum() *Activity_Provider {
	p := new(Activity_Provider)
	*p = x
	return p
}

func (x Activity_Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Activity_Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_techbridge_ap_metering_v1_activity_proto_enumTypes[0].Descriptor()
}

func (Activity_Provider) Type() protoreflect.EnumType {
	return &file_techbridge_ap_metering_v1_activity_proto_enumTypes[0]
}

func (x Activity_Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Activity_Provider.Descriptor instead.
func (Activity_Provider) EnumDescriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{0, 0}
}

type Activity_Status int32

const (
	Activity_STATUS_UNSPECIFIED Activity_Status = 0
	Activity_OK                 Activity_Status = 1
	Activity_FAILED             Activity_Status = 2
	Activity_DENIED             Activity_Status = 3
	Activity_TRUNCATED          Activity_Status = 4
)

// Enum value maps for Activity_Status.
var (
	Activity_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "OK",
		2: "FAILED",
		3: "DENIED",
		4: "TRUNCATED",
	}
	Activity_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"OK":                 1,
		"FAILED":             2,
		"DENIED":             3,
		"TRUNCATED":          4,
	}
)

func (x Activity_Status) Enum() *Activity_Status {
	p := new(Activity_Status)
	*p = x
	return p
}

func (x Activity_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Activity_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_techbridge_ap_metering_v1_activity_proto_enumTypes[1].Descriptor()
}

func (Activity_Status) Type() protoreflect.EnumType {
	return &file_techbridge_ap_metering_v1_activity_proto_enumTypes[1]
}

func (x Activity_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Activity_Status.Descriptor instead.
func (Activity_Status) EnumDescriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{0, 1}
}

type Activity struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Agent               string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Request             string                 `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Session             string                 `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	User                string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	CallerService       string                 `protobuf:"bytes,6,opt,name=caller_service,json=callerService,proto3" json:"caller_service,omitempty"`
	CallerComponent     string                 `protobuf:"bytes,7,opt,name=caller_component,json=callerComponent,proto3" json:"caller_component,omitempty"`
	Skill               string                 `protobuf:"bytes,8,opt,name=skill,proto3" json:"skill,omitempty"`
	Model               string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	Provider            Activity_Provider      `protobuf:"varint,10,opt,name=provider,proto3,enum=techbridge.ap.metering.v1.Activity_Provider" json:"provider,omitempty"`
	PromptTokens        int32                  `protobuf:"varint,11,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CandidateTokens     int32                  `protobuf:"varint,12,opt,name=candidate_tokens,json=candidateTokens,proto3" json:"candidate_tokens,omitempty"`
	CachedTokens        int32                  `protobuf:"varint,13,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	CacheWriteTokens    int32                  `protobuf:"varint,14,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	ReasoningTokens     int32                  `protobuf:"varint,15,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	TotalTokens         int32                  `protobuf:"varint,16,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	EstimatedCostMicros int64                  `protobuf:"varint,17,opt,name=estimated_cost_micros,json=estimatedCostMicros,proto3" json:"estimated_cost_micros,omitempty"`
	BilledCostMicros    int64                  `protobuf:"varint,18,opt,name=billed_cost_micros,json=billedCostMicros,proto3" json:"billed_cost_micros,omitempty"`
	RateCardVersion     string                 `protobuf:"bytes,19,opt,name=rate_card_version,json=rateCardVersion,proto3" json:"rate_card_version,omitempty"`
	Charges             []*Charge              `protobuf:"bytes,20,rep,name=charges,proto3" json:"charges,omitempty"`
	DurationMs          int64                  `protobuf:"varint,21,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Status              Activity_Status        `protobuf:"varint,22,opt,name=status,proto3,enum=techbridge.ap.metering.v1.Activity_Status" json:"status,omitempty"`
	ErrorCode           string                 `protobuf:"bytes,23,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	OccurredAt          *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Etag                string                 `protobuf:"bytes,97,opt,name=etag,proto3" json:"etag,omitempty"`
	CreateTime          *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime          *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{0}
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Activity) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Activity) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Activity) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Activity) GetCallerService() string {
	if x != nil {
		return x.CallerService
	}
	return ""
}

func (x *Activity) GetCallerComponent() string {
	if x != nil {
		return x.CallerComponent
	}
	return ""
}

func (x *Activity) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *Activity) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Activity) GetProvider() Activity_Provider {
	if x != nil {
		return x.Provider
	}
	return Activity_PROVIDER_UNSPECIFIED
}

func (x *Activity) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Activity) GetCandidateTokens() int32 {
	if x != nil {
		return x.CandidateTokens
	}
	return 0
}

func (x *Activity) GetCachedTokens() int32 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *Activity) GetCacheWriteTokens() int32 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *Activity) GetReasoningTokens() int32 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *Activity) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Activity) GetEstimatedCostMicros() int64 {
	if x != nil {
		return x.EstimatedCostMicros
	}
	return 0
}

func (x *Activity) GetBilledCostMicros() int64 {
	if x != nil {
		return x.BilledCostMicros
	}
	return 0
}

func (x *Activity) GetRateCardVersion() string {
	if x != nil {
		return x.RateCardVersion
	}
	return ""
}

func (x *Activity) GetCharges() []*Charge {
	if x != nil {
		return x.Charges
	}
	return nil
}

func (x *Activity) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Activity) GetStatus() Activity_Status {
	if x != nil {
		return x.Status
	}
	return Activity_STATUS_UNSPECIFIED
}

func (x *Activity) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Activity) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *Activity) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Activity) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Activity) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type Charge struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PriceableUnit       string                 `protobuf:"bytes,1,opt,name=priceable_unit,json=priceableUnit,proto3" json:"priceable_unit,omitempty"`
	Quantity            int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EstimatedCostMicros int64                  `protobuf:"varint,3,opt,name=estimated_cost_micros,json=estimatedCostMicros,proto3" json:"estimated_cost_micros,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Charge) Reset() {
	*x = Charge{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Charge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Charge) ProtoMessage() {}

func (x *Charge) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Charge.ProtoReflect.Descriptor instead.
func (*Charge) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{1}
}

func (x *Charge) GetPriceableUnit() string {
	if x != nil {
		return x.PriceableUnit
	}
	return ""
}

func (x *Charge) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Charge) GetEstimatedCostMicros() int64 {
	if x != nil {
		return x.EstimatedCostMicros
	}
	return 0
}

type CreateActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Activity      *Activity              `protobuf:"bytes,2,opt,name=activity,proto3" json:"activity,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{2}
}

func (x *CreateActivityRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateActivityRequest) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *CreateActivityRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type BatchCreateActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Activities    []*Activity            `protobuf:"bytes,2,rep,name=activities,proto3" json:"activities,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateActivitiesRequest) Reset() {
	*x = BatchCreateActivitiesRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateActivitiesRequest) ProtoMessage() {}

func (x *BatchCreateActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateActivitiesRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCreateActivitiesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchCreateActivitiesRequest) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *BatchCreateActivitiesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type BatchCreateActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateActivitiesResponse) Reset() {
	*x = BatchCreateActivitiesResponse{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateActivitiesResponse) ProtoMessage() {}

func (x *BatchCreateActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateActivitiesResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{4}
}

func (x *BatchCreateActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

type GetActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityRequest) Reset() {
	*x = GetActivityRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityRequest) ProtoMessage() {}

func (x *GetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityRequest.ProtoReflect.Descriptor instead.
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{5}
}

func (x *GetActivityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesRequest) Reset() {
	*x = ListActivitiesRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesRequest) ProtoMessage() {}

func (x *ListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{6}
}

func (x *ListActivitiesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListActivitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListActivitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListActivitiesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListActivitiesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesResponse) Reset() {
	*x = ListActivitiesResponse{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesResponse) ProtoMessage() {}

func (x *ListActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ListActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{7}
}

func (x *ListActivitiesResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ListActivitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type StreamListActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamListActivitiesRequest) Reset() {
	*x = StreamListActivitiesRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamListActivitiesRequest) ProtoMessage() {}

func (x *StreamListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*StreamListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{8}
}

func (x *StreamListActivitiesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *StreamListActivitiesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type AggregateActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	GroupBy       []string               `protobuf:"bytes,2,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateActivitiesRequest) Reset() {
	*x = AggregateActivitiesRequest{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateActivitiesRequest) ProtoMessage() {}

func (x *AggregateActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateActivitiesRequest.ProtoReflect.Descriptor instead.
func (*AggregateActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{9}
}

func (x *AggregateActivitiesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *AggregateActivitiesRequest) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *AggregateActivitiesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *AggregateActivitiesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AggregateActivitiesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *AggregateActivitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AggregateActivitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type AggregateActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*AggregateRow        `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateActivitiesResponse) Reset() {
	*x = AggregateActivitiesResponse{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateActivitiesResponse) ProtoMessage() {}

func (x *AggregateActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateActivitiesResponse.ProtoReflect.Descriptor instead.
func (*AggregateActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{10}
}

func (x *AggregateActivitiesResponse) GetRows() []*AggregateRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *AggregateActivitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type AggregateRow struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Dimensions          map[string]string      `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EstimatedCostMicros int64                  `protobuf:"varint,2,opt,name=estimated_cost_micros,json=estimatedCostMicros,proto3" json:"estimated_cost_micros,omitempty"`
	BilledCostMicros    int64                  `protobuf:"varint,3,opt,name=billed_cost_micros,json=billedCostMicros,proto3" json:"billed_cost_micros,omitempty"`
	TotalTokens         int64                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	ActivityCount       int64                  `protobuf:"varint,5,opt,name=activity_count,json=activityCount,proto3" json:"activity_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AggregateRow) Reset() {
	*x = AggregateRow{}
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRow) ProtoMessage() {}

func (x *AggregateRow) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRow.ProtoReflect.Descriptor instead.
func (*AggregateRow) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP(), []int{11}
}

func (x *AggregateRow) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *AggregateRow) GetEstimatedCostMicros() int64 {
	if x != nil {
		return x.EstimatedCostMicros
	}
	return 0
}

func (x *AggregateRow) GetBilledCostMicros() int64 {
	if x != nil {
		return x.BilledCostMicros
	}
	return 0
}

func (x *AggregateRow) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *AggregateRow) GetActivityCount() int64 {
	if x != nil {
		return x.ActivityCount
	}
	return 0
}

var File_techbridge_ap_metering_v1_activity_proto protoreflect.FileDescriptor

const file_techbridge_ap_metering_v1_activity_proto_rawDesc = "" +
	"\n" +
	"(techbridge/ap/metering/v1/activity.proto\x12\x19techbridge.ap.metering.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\v\n" +
	"\bActivity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\x05agent\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05agent\x12\x1e\n" +
	"\arequest\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\arequest\x12\x18\n" +
	"\asession\x18\x04 \x01(\tR\asession\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12%\n" +
	"\x0ecaller_service\x18\x06 \x01(\tR\rcallerService\x12)\n" +
	"\x10caller_component\x18\a \x01(\tR\x0fcallerComponent\x12\x14\n" +
	"\x05skill\x18\b \x01(\tR\x05skill\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12H\n" +
	"\bprovider\x18\n" +
	" \x01(\x0e2,.techbridge.ap.metering.v1.Activity.ProviderR\bprovider\x12#\n" +
	"\rprompt_tokens\x18\v \x01(\x05R\fpromptTokens\x12)\n" +
	"\x10candidate_tokens\x18\f \x01(\x05R\x0fcandidateTokens\x12#\n" +
	"\rcached_tokens\x18\r \x01(\x05R\fcachedTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x0e \x01(\x05R\x10cacheWriteTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x0f \x01(\x05R\x0freasoningTokens\x12!\n" +
	"\ftotal_tokens\x18\x10 \x01(\x05R\vtotalTokens\x128\n" +
	"\x15estimated_cost_micros\x18\x11 \x01(\x03B\x04\xe2A\x01\x03R\x13estimatedCostMicros\x122\n" +
	"\x12billed_cost_micros\x18\x12 \x01(\x03B\x04\xe2A\x01\x03R\x10billedCostMicros\x120\n" +
	"\x11rate_card_version\x18\x13 \x01(\tB\x04\xe2A\x01\x03R\x0frateCardVersion\x12;\n" +
	"\acharges\x18\x14 \x03(\v2!.techbridge.ap.metering.v1.ChargeR\acharges\x12\x1f\n" +
	"\vduration_ms\x18\x15 \x01(\x03R\n" +
	"durationMs\x12B\n" +
	"\x06status\x18\x16 \x01(\x0e2*.techbridge.ap.metering.v1.Activity.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x17 \x01(\tR\terrorCode\x12;\n" +
	"\voccurred_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x18\n" +
	"\x04etag\x18a \x01(\tB\x04\xe2A\x01\x03R\x04etag\x12A\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime\"^\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tVERTEX_AI\x10\x01\x12\r\n" +
	"\tANTHROPIC\x10\x02\x12\n" +
	"\n" +
	"\x06OPENAI\x10\x03\x12\x0e\n" +
	"\n" +
	"PERPLEXITY\x10\x04\"O\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\n" +
	"\n" +
	"\x06DENIED\x10\x03\x12\r\n" +
	"\tTRUNCATED\x10\x04:X\xeaAU\n" +
	"\x1fmetering.ap.techbridge/Activity\x122organisations/{organisation}/activities/{activity}\"\x91\x01\n" +
	"\x06Charge\x12+\n" +
	"\x0epriceable_unit\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\rpriceableUnit\x12 \n" +
	"\bquantity\x18\x02 \x01(\x03B\x04\xe2A\x01\x02R\bquantity\x128\n" +
	"\x15estimated_cost_micros\x18\x03 \x01(\x03B\x04\xe2A\x01\x03R\x13estimatedCostMicros\"\x9b\x01\n" +
	"\x15CreateActivityRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12E\n" +
	"\bactivity\x18\x02 \x01(\v2#.techbridge.ap.metering.v1.ActivityB\x04\xe2A\x01\x02R\bactivity\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\xa6\x01\n" +
	"\x1cBatchCreateActivitiesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12I\n" +
	"\n" +
	"activities\x18\x02 \x03(\v2#.techbridge.ap.metering.v1.ActivityB\x04\xe2A\x01\x02R\n" +
	"activities\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"d\n" +
	"\x1dBatchCreateActivitiesResponse\x12C\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2#.techbridge.ap.metering.v1.ActivityR\n" +
	"activities\".\n" +
	"\x12GetActivityRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\"\xa4\x01\n" +
	"\x15ListActivitiesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\"\x85\x01\n" +
	"\x16ListActivitiesResponse\x12C\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2#.techbridge.ap.metering.v1.ActivityR\n" +
	"activities\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"S\n" +
	"\x1bStreamListActivitiesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\"\xa7\x02\n" +
	"\x1aAggregateActivitiesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x19\n" +
	"\bgroup_by\x18\x02 \x03(\tR\agroupBy\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12?\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x02R\tstartTime\x12;\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x02R\aendTime\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\"\x82\x01\n" +
	"\x1bAggregateActivitiesResponse\x12;\n" +
	"\x04rows\x18\x01 \x03(\v2'.techbridge.ap.metering.v1.AggregateRowR\x04rows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd2\x02\n" +
	"\fAggregateRow\x12W\n" +
	"\n" +
	"dimensions\x18\x01 \x03(\v27.techbridge.ap.metering.v1.AggregateRow.DimensionsEntryR\n" +
	"dimensions\x122\n" +
	"\x15estimated_cost_micros\x18\x02 \x01(\x03R\x13estimatedCostMicros\x12,\n" +
	"\x12billed_cost_micros\x18\x03 \x01(\x03R\x10billedCostMicros\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x03R\vtotalTokens\x12%\n" +
	"\x0eactivity_count\x18\x05 \x01(\x03R\ractivityCount\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xed\x05\n" +
	"\x11ActivitiesService\x12i\n" +
	"\x0eCreateActivity\x120.techbridge.ap.metering.v1.CreateActivityRequest\x1a#.techbridge.ap.metering.v1.Activity\"\x00\x12\x8c\x01\n" +
	"\x15BatchCreateActivities\x127.techbridge.ap.metering.v1.BatchCreateActivitiesRequest\x1a8.techbridge.ap.metering.v1.BatchCreateActivitiesResponse\"\x00\x12c\n" +
	"\vGetActivity\x12-.techbridge.ap.metering.v1.GetActivityRequest\x1a#.techbridge.ap.metering.v1.Activity\"\x00\x12w\n" +
	"\x0eListActivities\x120.techbridge.ap.metering.v1.ListActivitiesRequest\x1a1.techbridge.ap.metering.v1.ListActivitiesResponse\"\x00\x12\x86\x01\n" +
	"\x13AggregateActivities\x125.techbridge.ap.metering.v1.AggregateActivitiesRequest\x1a6.techbridge.ap.metering.v1.AggregateActivitiesResponse\"\x00\x12w\n" +
	"\x14StreamListActivities\x126.techbridge.ap.metering.v1.StreamListActivitiesRequest\x1a#.techbridge.ap.metering.v1.Activity\"\x000\x01B#Z!alis.build/techbridge/ap/meteringb\x06proto3"

var (
	file_techbridge_ap_metering_v1_activity_proto_rawDescOnce sync.Once
	file_techbridge_ap_metering_v1_activity_proto_rawDescData []byte
)

func file_techbridge_ap_metering_v1_activity_proto_rawDescGZIP() []byte {
	file_techbridge_ap_metering_v1_activity_proto_rawDescOnce.Do(func() {
		file_techbridge_ap_metering_v1_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_activity_proto_rawDesc), len(file_techbridge_ap_metering_v1_activity_proto_rawDesc)))
	})
	return file_techbridge_ap_metering_v1_activity_proto_rawDescData
}

var file_techbridge_ap_metering_v1_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_techbridge_ap_metering_v1_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_techbridge_ap_metering_v1_activity_proto_goTypes = []any{
	(Activity_Provider)(0),                // 0: techbridge.ap.metering.v1.Activity.Provider
	(Activity_Status)(0),                  // 1: techbridge.ap.metering.v1.Activity.Status
	(*Activity)(nil),                      // 2: techbridge.ap.metering.v1.Activity
	(*Charge)(nil),                        // 3: techbridge.ap.metering.v1.Charge
	(*CreateActivityRequest)(nil),         // 4: techbridge.ap.metering.v1.CreateActivityRequest
	(*BatchCreateActivitiesRequest)(nil),  // 5: techbridge.ap.metering.v1.BatchCreateActivitiesRequest
	(*BatchCreateActivitiesResponse)(nil), // 6: techbridge.ap.metering.v1.BatchCreateActivitiesResponse
	(*GetActivityRequest)(nil),            // 7: techbridge.ap.metering.v1.GetActivityRequest
	(*ListActivitiesRequest)(nil),         // 8: techbridge.ap.metering.v1.ListActivitiesRequest
	(*ListActivitiesResponse)(nil),        // 9: techbridge.ap.metering.v1.ListActivitiesResponse
	(*StreamListActivitiesRequest)(nil),   // 10: techbridge.ap.metering.v1.StreamListActivitiesRequest
	(*AggregateActivitiesRequest)(nil),    // 11: techbridge.ap.metering.v1.AggregateActivitiesRequest
	(*AggregateActivitiesResponse)(nil),   // 12: techbridge.ap.metering.v1.AggregateActivitiesResponse
	(*AggregateRow)(nil),                  // 13: techbridge.ap.metering.v1.AggregateRow
	nil,                                   // 14: techbridge.ap.metering.v1.AggregateRow.DimensionsEntry
	(*timestamppb.Timestamp)(nil),         // 15: google.protobuf.Timestamp
}
var file_techbridge_ap_metering_v1_activity_proto_depIdxs = []int32{
	0,  // 0: techbridge.ap.metering.v1.Activity.provider:type_name -> techbridge.ap.metering.v1.Activity.Provider
	3,  // 1: techbridge.ap.metering.v1.Activity.charges:type_name -> techbridge.ap.metering.v1.Charge
	1,  // 2: techbridge.ap.metering.v1.Activity.status:type_name -> techbridge.ap.metering.v1.Activity.Status
	15, // 3: techbridge.ap.metering.v1.Activity.occurred_at:type_name -> google.protobuf.Timestamp
	15, // 4: techbridge.ap.metering.v1.Activity.create_time:type_name -> google.protobuf.Timestamp
	15, // 5: techbridge.ap.metering.v1.Activity.update_time:type_name -> google.protobuf.Timestamp
	2,  // 6: techbridge.ap.metering.v1.CreateActivityRequest.activity:type_name -> techbridge.ap.metering.v1.Activity
	2,  // 7: techbridge.ap.metering.v1.BatchCreateActivitiesRequest.activities:type_name -> techbridge.ap.metering.v1.Activity
	2,  // 8: techbridge.ap.metering.v1.BatchCreateActivitiesResponse.activities:type_name -> techbridge.ap.metering.v1.Activity
	2,  // 9: techbridge.ap.metering.v1.ListActivitiesResponse.activities:type_name -> techbridge.ap.metering.v1.Activity
	15, // 10: techbridge.ap.metering.v1.AggregateActivitiesRequest.start_time:type_name -> google.protobuf.Timestamp
	15, // 11: techbridge.ap.metering.v1.AggregateActivitiesRequest.end_time:type_name -> google.protobuf.Timestamp
	13, // 12: techbridge.ap.metering.v1.AggregateActivitiesResponse.rows:type_name -> techbridge.ap.metering.v1.AggregateRow
	14, // 13: techbridge.ap.metering.v1.AggregateRow.dimensions:type_name -> techbridge.ap.metering.v1.AggregateRow.DimensionsEntry
	4,  // 14: techbridge.ap.metering.v1.ActivitiesService.CreateActivity:input_type -> techbridge.ap.metering.v1.CreateActivityRequest
	5,  // 15: techbridge.ap.metering.v1.ActivitiesService.BatchCreateActivities:input_type -> techbridge.ap.metering.v1.BatchCreateActivitiesRequest
	7,  // 16: techbridge.ap.metering.v1.ActivitiesService.GetActivity:input_type -> techbridge.ap.metering.v1.GetActivityRequest
	8,  // 17: techbridge.ap.metering.v1.ActivitiesService.ListActivities:input_type -> techbridge.ap.metering.v1.ListActivitiesRequest
	11, // 18: techbridge.ap.metering.v1.ActivitiesService.AggregateActivities:input_type -> techbridge.ap.metering.v1.AggregateActivitiesRequest
	10, // 19: techbridge.ap.metering.v1.ActivitiesService.StreamListActivities:input_type -> techbridge.ap.metering.v1.StreamListActivitiesRequest
	2,  // 20: techbridge.ap.metering.v1.ActivitiesService.CreateActivity:output_type -> techbridge.ap.metering.v1.Activity
	6,  // 21: techbridge.ap.metering.v1.ActivitiesService.BatchCreateActivities:output_type -> techbridge.ap.metering.v1.BatchCreateActivitiesResponse
	2,  // 22: techbridge.ap.metering.v1.ActivitiesService.GetActivity:output_type -> techbridge.ap.metering.v1.Activity
	9,  // 23: techbridge.ap.metering.v1.ActivitiesService.ListActivities:output_type -> techbridge.ap.metering.v1.ListActivitiesResponse
	12, // 24: techbridge.ap.metering.v1.ActivitiesService.AggregateActivities:output_type -> techbridge.ap.metering.v1.AggregateActivitiesResponse
	2,  // 25: techbridge.ap.metering.v1.ActivitiesService.StreamListActivities:output_type -> techbridge.ap.metering.v1.Activity
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_techbridge_ap_metering_v1_activity_proto_init() }
func file_techbridge_ap_metering_v1_activity_proto_init() {
	if File_techbridge_ap_metering_v1_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_activity_proto_rawDesc), len(file_techbridge_ap_metering_v1_activity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techbridge_ap_metering_v1_activity_proto_goTypes,
		DependencyIndexes: file_techbridge_ap_metering_v1_activity_proto_depIdxs,
		EnumInfos:         file_techbridge_ap_metering_v1_activity_proto_enumTypes,
		MessageInfos:      file_techbridge_ap_metering_v1_activity_proto_msgTypes,
	}.Build()
	File_techbridge_ap_metering_v1_activity_proto = out.File
	file_techbridge_ap_metering_v1_activity_proto_goTypes = nil
	file_techbridge_ap_metering_v1_activity_proto_depIdxs = nil
}
