// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: techbridge/ap/metering/v1/agent.proto

package metering

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Product       string                 `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Components    []string               `protobuf:"bytes,6,rep,name=components,proto3" json:"components,omitempty"`
	Etag          string                 `protobuf:"bytes,97,opt,name=etag,proto3" json:"etag,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Agent) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Agent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Agent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Agent) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Agent) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Agent) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Agent) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CreateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Agent         *Agent                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *CreateAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *UpdateAgentRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_techbridge_ap_metering_v1_agent_proto protoreflect.FileDescriptor

const file_techbridge_ap_metering_v1_agent_proto_rawDesc = "" +
	"\n" +
	"%techbridge/ap/metering/v1/agent.proto\x12\x19techbridge.ap.metering.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x03\n" +
	"\x05Agent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vdisplayName\x12\x1e\n" +
	"\aproduct\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\aproduct\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x1a\n" +
	"\x05owner\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\x05owner\x12\x1e\n" +
	"\n" +
	"components\x18\x06 \x03(\tR\n" +
	"components\x12\x18\n" +
	"\x04etag\x18a \x01(\tB\x04\xe2A\x01\x03R\x04etag\x12A\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime:N\xeaAK\n" +
	"\x1cmetering.ap.techbridge/Agent\x12+organisations/{organisation}/agents/{agent}\"\x8b\x01\n" +
	"\x12CreateAgentRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12<\n" +
	"\x05agent\x18\x02 \x01(\v2 .techbridge.ap.metering.v1.AgentB\x04\xe2A\x01\x02R\x05agent\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"+\n" +
	"\x0fGetAgentRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\"\x8f\x01\n" +
	"\x12UpdateAgentRequest\x12<\n" +
	"\x05agent\x18\x01 \x01(\v2 .techbridge.ap.metering.v1.AgentB\x04\xe2A\x01\x02R\x05agent\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"m\n" +
	"\x11ListAgentsRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"v\n" +
	"\x12ListAgentsResponse\x128\n" +
	"\x06agents\x18\x01 \x03(\v2 .techbridge.ap.metering.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x9c\x03\n" +
	"\rAgentsService\x12`\n" +
	"\vCreateAgent\x12-.techbridge.ap.metering.v1.CreateAgentRequest\x1a .techbridge.ap.metering.v1.Agent\"\x00\x12Z\n" +
	"\bGetAgent\x12*.techbridge.ap.metering.v1.GetAgentRequest\x1a .techbridge.ap.metering.v1.Agent\"\x00\x12`\n" +
	"\vUpdateAgent\x12-.techbridge.ap.metering.v1.UpdateAgentRequest\x1a .techbridge.ap.metering.v1.Agent\"\x00\x12k\n" +
	"\n" +
	"ListAgents\x12,.techbridge.ap.metering.v1.ListAgentsRequest\x1a-.techbridge.ap.metering.v1.ListAgentsResponse\"\x00B#Z!alis.build/techbridge/ap/meteringb\x06proto3"

var (
	file_techbridge_ap_metering_v1_agent_proto_rawDescOnce sync.Once
	file_techbridge_ap_metering_v1_agent_proto_rawDescData []byte
)

func file_techbridge_ap_metering_v1_agent_proto_rawDescGZIP() []byte {
	file_techbridge_ap_metering_v1_agent_proto_rawDescOnce.Do(func() {
		file_techbridge_ap_metering_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_agent_proto_rawDesc), len(file_techbridge_ap_metering_v1_agent_proto_rawDesc)))
	})
	return file_techbridge_ap_metering_v1_agent_proto_rawDescData
}

var file_techbridge_ap_metering_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_techbridge_ap_metering_v1_agent_proto_goTypes = []any{
	(*Agent)(nil),                 // 0: techbridge.ap.metering.v1.Agent
	(*CreateAgentRequest)(nil),    // 1: techbridge.ap.metering.v1.CreateAgentRequest
	(*GetAgentRequest)(nil),       // 2: techbridge.ap.metering.v1.GetAgentRequest
	(*UpdateAgentRequest)(nil),    // 3: techbridge.ap.metering.v1.UpdateAgentRequest
	(*ListAgentsRequest)(nil),     // 4: techbridge.ap.metering.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 5: techbridge.ap.metering.v1.ListAgentsResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 7: google.protobuf.FieldMask
}
var file_techbridge_ap_metering_v1_agent_proto_depIdxs = []int32{
	6,  // 0: techbridge.ap.metering.v1.Agent.create_time:type_name -> google.protobuf.Timestamp
	6,  // 1: techbridge.ap.metering.v1.Agent.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: techbridge.ap.metering.v1.CreateAgentRequest.agent:type_name -> techbridge.ap.metering.v1.Agent
	0,  // 3: techbridge.ap.metering.v1.UpdateAgentRequest.agent:type_name -> techbridge.ap.metering.v1.Agent
	7,  // 4: techbridge.ap.metering.v1.UpdateAgentRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 5: techbridge.ap.metering.v1.ListAgentsResponse.agents:type_name -> techbridge.ap.metering.v1.Agent
	1,  // 6: techbridge.ap.metering.v1.AgentsService.CreateAgent:input_type -> techbridge.ap.metering.v1.CreateAgentRequest
	2,  // 7: techbridge.ap.metering.v1.AgentsService.GetAgent:input_type -> techbridge.ap.metering.v1.GetAgentRequest
	3,  // 8: techbridge.ap.metering.v1.AgentsService.UpdateAgent:input_type -> techbridge.ap.metering.v1.UpdateAgentRequest
	4,  // 9: techbridge.ap.metering.v1.AgentsService.ListAgents:input_type -> techbridge.ap.metering.v1.ListAgentsRequest
	0,  // 10: techbridge.ap.metering.v1.AgentsService.CreateAgent:output_type -> techbridge.ap.metering.v1.Agent
	0,  // 11: techbridge.ap.metering.v1.AgentsService.GetAgent:output_type -> techbridge.ap.metering.v1.Agent
	0,  // 12: techbridge.ap.metering.v1.AgentsService.UpdateAgent:output_type -> techbridge.ap.metering.v1.Agent
	5,  // 13: techbridge.ap.metering.v1.AgentsService.ListAgents:output_type -> techbridge.ap.metering.v1.ListAgentsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_techbridge_ap_metering_v1_agent_proto_init() }
func file_techbridge_ap_metering_v1_agent_proto_init() {
	if File_techbridge_ap_metering_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_agent_proto_rawDesc), len(file_techbridge_ap_metering_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techbridge_ap_metering_v1_agent_proto_goTypes,
		DependencyIndexes: file_techbridge_ap_metering_v1_agent_proto_depIdxs,
		MessageInfos:      file_techbridge_ap_metering_v1_agent_proto_msgTypes,
	}.Build()
	File_techbridge_ap_metering_v1_agent_proto = out.File
	file_techbridge_ap_metering_v1_agent_proto_goTypes = nil
	file_techbridge_ap_metering_v1_agent_proto_depIdxs = nil
}
