// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: techbridge/ap/metering/v1/agent.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-15 11:20:12 UTC

package metering

const (
	// AgentsService_CreateAgent_FullMethodDescription returns the description of the techbridge.ap.metering.v1.AgentsService.CreateAgent method.
	AgentsService_CreateAgent_FullMethodDescription = "Registers a new agent."
	// AgentsService_GetAgent_FullMethodDescription returns the description of the techbridge.ap.metering.v1.AgentsService.GetAgent method.
	AgentsService_GetAgent_FullMethodDescription = "Returns a single agent by resource name."
	// AgentsService_UpdateAgent_FullMethodDescription returns the description of the techbridge.ap.metering.v1.AgentsService.UpdateAgent method.
	AgentsService_UpdateAgent_FullMethodDescription = "Updates an agent, typically to add a component or change its owner."
	// AgentsService_ListAgents_FullMethodDescription returns the description of the techbridge.ap.metering.v1.AgentsService.ListAgents method.
	AgentsService_ListAgents_FullMethodDescription = "Lists the agents registered to an organisation."
)
