// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: techbridge/ap/metering/v1/agent.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-03 14:32:42 UTC

package metering

const (
	// AgentsService_CreateAgent_FullMethodDescription returns the description of the techbridge.ap.metering.v1.AgentsService.CreateAgent method.
	AgentsService_CreateAgent_FullMethodDescription = ""
	// AgentsService_GetAgent_FullMethodDescription returns the description of the techbridge.ap.metering.v1.AgentsService.GetAgent method.
	AgentsService_GetAgent_FullMethodDescription = ""
	// AgentsService_UpdateAgent_FullMethodDescription returns the description of the techbridge.ap.metering.v1.AgentsService.UpdateAgent method.
	AgentsService_UpdateAgent_FullMethodDescription = ""
	// AgentsService_ListAgents_FullMethodDescription returns the description of the techbridge.ap.metering.v1.AgentsService.ListAgents method.
	AgentsService_ListAgents_FullMethodDescription = ""
)
