// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: techbridge/ap/metering/v1/outcome.proto

package metering

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutcomeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Etag          string                 `protobuf:"bytes,97,opt,name=etag,proto3" json:"etag,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutcomeDefinition) Reset() {
	*x = OutcomeDefinition{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutcomeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeDefinition) ProtoMessage() {}

func (x *OutcomeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeDefinition.ProtoReflect.Descriptor instead.
func (*OutcomeDefinition) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{0}
}

func (x *OutcomeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutcomeDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OutcomeDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OutcomeDefinition) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *OutcomeDefinition) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *OutcomeDefinition) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *OutcomeDefinition) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type Outcome struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OutcomeDefinition string                 `protobuf:"bytes,2,opt,name=outcome_definition,json=outcomeDefinition,proto3" json:"outcome_definition,omitempty"`
	Request           string                 `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Quantity          int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Etag              string                 `protobuf:"bytes,97,opt,name=etag,proto3" json:"etag,omitempty"`
	CreateTime        *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime        *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{1}
}

func (x *Outcome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Outcome) GetOutcomeDefinition() string {
	if x != nil {
		return x.OutcomeDefinition
	}
	return ""
}

func (x *Outcome) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Outcome) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Outcome) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *Outcome) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Outcome) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Outcome) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CreateOutcomeDefinitionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Parent              string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	OutcomeDefinition   *OutcomeDefinition     `protobuf:"bytes,2,opt,name=outcome_definition,json=outcomeDefinition,proto3" json:"outcome_definition,omitempty"`
	OutcomeDefinitionId string                 `protobuf:"bytes,3,opt,name=outcome_definition_id,json=outcomeDefinitionId,proto3" json:"outcome_definition_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOutcomeDefinitionRequest) Reset() {
	*x = CreateOutcomeDefinitionRequest{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOutcomeDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOutcomeDefinitionRequest) ProtoMessage() {}

func (x *CreateOutcomeDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOutcomeDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateOutcomeDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOutcomeDefinitionRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateOutcomeDefinitionRequest) GetOutcomeDefinition() *OutcomeDefinition {
	if x != nil {
		return x.OutcomeDefinition
	}
	return nil
}

func (x *CreateOutcomeDefinitionRequest) GetOutcomeDefinitionId() string {
	if x != nil {
		return x.OutcomeDefinitionId
	}
	return ""
}

type GetOutcomeDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutcomeDefinitionRequest) Reset() {
	*x = GetOutcomeDefinitionRequest{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutcomeDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutcomeDefinitionRequest) ProtoMessage() {}

func (x *GetOutcomeDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutcomeDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetOutcomeDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{3}
}

func (x *GetOutcomeDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateOutcomeDefinitionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OutcomeDefinition *OutcomeDefinition     `protobuf:"bytes,1,opt,name=outcome_definition,json=outcomeDefinition,proto3" json:"outcome_definition,omitempty"`
	UpdateMask        *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateOutcomeDefinitionRequest) Reset() {
	*x = UpdateOutcomeDefinitionRequest{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOutcomeDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOutcomeDefinitionRequest) ProtoMessage() {}

func (x *UpdateOutcomeDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOutcomeDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateOutcomeDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOutcomeDefinitionRequest) GetOutcomeDefinition() *OutcomeDefinition {
	if x != nil {
		return x.OutcomeDefinition
	}
	return nil
}

func (x *UpdateOutcomeDefinitionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ListOutcomeDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutcomeDefinitionsRequest) Reset() {
	*x = ListOutcomeDefinitionsRequest{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutcomeDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutcomeDefinitionsRequest) ProtoMessage() {}

func (x *ListOutcomeDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutcomeDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListOutcomeDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{5}
}

func (x *ListOutcomeDefinitionsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListOutcomeDefinitionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOutcomeDefinitionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOutcomeDefinitionsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OutcomeDefinitions []*OutcomeDefinition   `protobuf:"bytes,1,rep,name=outcome_definitions,json=outcomeDefinitions,proto3" json:"outcome_definitions,omitempty"`
	NextPageToken      string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListOutcomeDefinitionsResponse) Reset() {
	*x = ListOutcomeDefinitionsResponse{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutcomeDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutcomeDefinitionsResponse) ProtoMessage() {}

func (x *ListOutcomeDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutcomeDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListOutcomeDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{6}
}

func (x *ListOutcomeDefinitionsResponse) GetOutcomeDefinitions() []*OutcomeDefinition {
	if x != nil {
		return x.OutcomeDefinitions
	}
	return nil
}

func (x *ListOutcomeDefinitionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateOutcomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Outcome       *Outcome               `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOutcomeRequest) Reset() {
	*x = CreateOutcomeRequest{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOutcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOutcomeRequest) ProtoMessage() {}

func (x *CreateOutcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOutcomeRequest.ProtoReflect.Descriptor instead.
func (*CreateOutcomeRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOutcomeRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateOutcomeRequest) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *CreateOutcomeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ListOutcomesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutcomesRequest) Reset() {
	*x = ListOutcomesRequest{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutcomesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutcomesRequest) ProtoMessage() {}

func (x *ListOutcomesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutcomesRequest.ProtoReflect.Descriptor instead.
func (*ListOutcomesRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{8}
}

func (x *ListOutcomesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListOutcomesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOutcomesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOutcomesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListOutcomesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcomes      []*Outcome             `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutcomesResponse) Reset() {
	*x = ListOutcomesResponse{}
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutcomesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutcomesResponse) ProtoMessage() {}

func (x *ListOutcomesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_outcome_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutcomesResponse.ProtoReflect.Descriptor instead.
func (*ListOutcomesResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP(), []int{9}
}

func (x *ListOutcomesResponse) GetOutcomes() []*Outcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *ListOutcomesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_techbridge_ap_metering_v1_outcome_proto protoreflect.FileDescriptor

const file_techbridge_ap_metering_v1_outcome_proto_rawDesc = "" +
	"\n" +
	"'techbridge/ap/metering/v1/outcome.proto\x12\x19techbridge.ap.metering.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x03\n" +
	"\x11OutcomeDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\x04unit\x18\x04 \x01(\tB\x04\xe2A\x01\x02R\x04unit\x12\x18\n" +
	"\x04etag\x18a \x01(\tB\x04\xe2A\x01\x03R\x04etag\x12A\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime:s\xeaAp\n" +
	"(metering.ap.techbridge/OutcomeDefinition\x12Dorganisations/{organisation}/outcomeDefinitions/{outcome_definition}\"\xc7\x03\n" +
	"\aOutcome\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x12outcome_definition\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x11outcomeDefinition\x12\x1e\n" +
	"\arequest\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\arequest\x12 \n" +
	"\bquantity\x18\x04 \x01(\x03B\x04\xe2A\x01\x02R\bquantity\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x18\n" +
	"\x04etag\x18a \x01(\tB\x04\xe2A\x01\x03R\x04etag\x12A\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime:T\xeaAQ\n" +
	"\x1emetering.ap.techbridge/Outcome\x12/organisations/{organisation}/outcomes/{outcome}\"\xd5\x01\n" +
	"\x1eCreateOutcomeDefinitionRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12a\n" +
	"\x12outcome_definition\x18\x02 \x01(\v2,.techbridge.ap.metering.v1.OutcomeDefinitionB\x04\xe2A\x01\x02R\x11outcomeDefinition\x122\n" +
	"\x15outcome_definition_id\x18\x03 \x01(\tR\x13outcomeDefinitionId\"7\n" +
	"\x1bGetOutcomeDefinitionRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\"\xc0\x01\n" +
	"\x1eUpdateOutcomeDefinitionRequest\x12a\n" +
	"\x12outcome_definition\x18\x01 \x01(\v2,.techbridge.ap.metering.v1.OutcomeDefinitionB\x04\xe2A\x01\x02R\x11outcomeDefinition\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"y\n" +
	"\x1dListOutcomeDefinitionsRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xa7\x01\n" +
	"\x1eListOutcomeDefinitionsResponse\x12]\n" +
	"\x13outcome_definitions\x18\x01 \x03(\v2,.techbridge.ap.metering.v1.OutcomeDefinitionR\x12outcomeDefinitions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x97\x01\n" +
	"\x14CreateOutcomeRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12B\n" +
	"\aoutcome\x18\x02 \x01(\v2\".techbridge.ap.metering.v1.OutcomeB\x04\xe2A\x01\x02R\aoutcome\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\x87\x01\n" +
	"\x13ListOutcomesRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"~\n" +
	"\x14ListOutcomesResponse\x12>\n" +
	"\boutcomes\x18\x01 \x03(\v2\".techbridge.ap.metering.v1.OutcomeR\boutcomes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x8c\x06\n" +
	"\x0fOutcomesService\x12\x84\x01\n" +
	"\x17CreateOutcomeDefinition\x129.techbridge.ap.metering.v1.CreateOutcomeDefinitionRequest\x1a,.techbridge.ap.metering.v1.OutcomeDefinition\"\x00\x12~\n" +
	"\x14GetOutcomeDefinition\x126.techbridge.ap.metering.v1.GetOutcomeDefinitionRequest\x1a,.techbridge.ap.metering.v1.OutcomeDefinition\"\x00\x12\x84\x01\n" +
	"\x17UpdateOutcomeDefinition\x129.techbridge.ap.metering.v1.UpdateOutcomeDefinitionRequest\x1a,.techbridge.ap.metering.v1.OutcomeDefinition\"\x00\x12\x8f\x01\n" +
	"\x16ListOutcomeDefinitions\x128.techbridge.ap.metering.v1.ListOutcomeDefinitionsRequest\x1a9.techbridge.ap.metering.v1.ListOutcomeDefinitionsResponse\"\x00\x12f\n" +
	"\rCreateOutcome\x12/.techbridge.ap.metering.v1.CreateOutcomeRequest\x1a\".techbridge.ap.metering.v1.Outcome\"\x00\x12q\n" +
	"\fListOutcomes\x12..techbridge.ap.metering.v1.ListOutcomesRequest\x1a/.techbridge.ap.metering.v1.ListOutcomesResponse\"\x00B#Z!alis.build/techbridge/ap/meteringb\x06proto3"

var (
	file_techbridge_ap_metering_v1_outcome_proto_rawDescOnce sync.Once
	file_techbridge_ap_metering_v1_outcome_proto_rawDescData []byte
)

func file_techbridge_ap_metering_v1_outcome_proto_rawDescGZIP() []byte {
	file_techbridge_ap_metering_v1_outcome_proto_rawDescOnce.Do(func() {
		file_techbridge_ap_metering_v1_outcome_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_outcome_proto_rawDesc), len(file_techbridge_ap_metering_v1_outcome_proto_rawDesc)))
	})
	return file_techbridge_ap_metering_v1_outcome_proto_rawDescData
}

var file_techbridge_ap_metering_v1_outcome_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_techbridge_ap_metering_v1_outcome_proto_goTypes = []any{
	(*OutcomeDefinition)(nil),              // 0: techbridge.ap.metering.v1.OutcomeDefinition
	(*Outcome)(nil),                        // 1: techbridge.ap.metering.v1.Outcome
	(*CreateOutcomeDefinitionRequest)(nil), // 2: techbridge.ap.metering.v1.CreateOutcomeDefinitionRequest
	(*GetOutcomeDefinitionRequest)(nil),    // 3: techbridge.ap.metering.v1.GetOutcomeDefinitionRequest
	(*UpdateOutcomeDefinitionRequest)(nil), // 4: techbridge.ap.metering.v1.UpdateOutcomeDefinitionRequest
	(*ListOutcomeDefinitionsRequest)(nil),  // 5: techbridge.ap.metering.v1.ListOutcomeDefinitionsRequest
	(*ListOutcomeDefinitionsResponse)(nil), // 6: techbridge.ap.metering.v1.ListOutcomeDefinitionsResponse
	(*CreateOutcomeRequest)(nil),           // 7: techbridge.ap.metering.v1.CreateOutcomeRequest
	(*ListOutcomesRequest)(nil),            // 8: techbridge.ap.metering.v1.ListOutcomesRequest
	(*ListOutcomesResponse)(nil),           // 9: techbridge.ap.metering.v1.ListOutcomesResponse
	(*timestamppb.Timestamp)(nil),          // 10: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),          // 11: google.protobuf.FieldMask
}
var file_techbridge_ap_metering_v1_outcome_proto_depIdxs = []int32{
	10, // 0: techbridge.ap.metering.v1.OutcomeDefinition.create_time:type_name -> google.protobuf.Timestamp
	10, // 1: techbridge.ap.metering.v1.OutcomeDefinition.update_time:type_name -> google.protobuf.Timestamp
	10, // 2: techbridge.ap.metering.v1.Outcome.occurred_at:type_name -> google.protobuf.Timestamp
	10, // 3: techbridge.ap.metering.v1.Outcome.create_time:type_name -> google.protobuf.Timestamp
	10, // 4: techbridge.ap.metering.v1.Outcome.update_time:type_name -> google.protobuf.Timestamp
	0,  // 5: techbridge.ap.metering.v1.CreateOutcomeDefinitionRequest.outcome_definition:type_name -> techbridge.ap.metering.v1.OutcomeDefinition
	0,  // 6: techbridge.ap.metering.v1.UpdateOutcomeDefinitionRequest.outcome_definition:type_name -> techbridge.ap.metering.v1.OutcomeDefinition
	11, // 7: techbridge.ap.metering.v1.UpdateOutcomeDefinitionRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 8: techbridge.ap.metering.v1.ListOutcomeDefinitionsResponse.outcome_definitions:type_name -> techbridge.ap.metering.v1.OutcomeDefinition
	1,  // 9: techbridge.ap.metering.v1.CreateOutcomeRequest.outcome:type_name -> techbridge.ap.metering.v1.Outcome
	1,  // 10: techbridge.ap.metering.v1.ListOutcomesResponse.outcomes:type_name -> techbridge.ap.metering.v1.Outcome
	2,  // 11: techbridge.ap.metering.v1.OutcomesService.CreateOutcomeDefinition:input_type -> techbridge.ap.metering.v1.CreateOutcomeDefinitionRequest
	3,  // 12: techbridge.ap.metering.v1.OutcomesService.GetOutcomeDefinition:input_type -> techbridge.ap.metering.v1.GetOutcomeDefinitionRequest
	4,  // 13: techbridge.ap.metering.v1.OutcomesService.UpdateOutcomeDefinition:input_type -> techbridge.ap.metering.v1.UpdateOutcomeDefinitionRequest
	5,  // 14: techbridge.ap.metering.v1.OutcomesService.ListOutcomeDefinitions:input_type -> techbridge.ap.metering.v1.ListOutcomeDefinitionsRequest
	7,  // 15: techbridge.ap.metering.v1.OutcomesService.CreateOutcome:input_type -> techbridge.ap.metering.v1.CreateOutcomeRequest
	8,  // 16: techbridge.ap.metering.v1.OutcomesService.ListOutcomes:input_type -> techbridge.ap.metering.v1.ListOutcomesRequest
	0,  // 17: techbridge.ap.metering.v1.OutcomesService.CreateOutcomeDefinition:output_type -> techbridge.ap.metering.v1.OutcomeDefinition
	0,  // 18: techbridge.ap.metering.v1.OutcomesService.GetOutcomeDefinition:output_type -> techbridge.ap.metering.v1.OutcomeDefinition
	0,  // 19: techbridge.ap.metering.v1.OutcomesService.UpdateOutcomeDefinition:output_type -> techbridge.ap.metering.v1.OutcomeDefinition
	6,  // 20: techbridge.ap.metering.v1.OutcomesService.ListOutcomeDefinitions:output_type -> techbridge.ap.metering.v1.ListOutcomeDefinitionsResponse
	1,  // 21: techbridge.ap.metering.v1.OutcomesService.CreateOutcome:output_type -> techbridge.ap.metering.v1.Outcome
	9,  // 22: techbridge.ap.metering.v1.OutcomesService.ListOutcomes:output_type -> techbridge.ap.metering.v1.ListOutcomesResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_techbridge_ap_metering_v1_outcome_proto_init() }
func file_techbridge_ap_metering_v1_outcome_proto_init() {
	if File_techbridge_ap_metering_v1_outcome_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_outcome_proto_rawDesc), len(file_techbridge_ap_metering_v1_outcome_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techbridge_ap_metering_v1_outcome_proto_goTypes,
		DependencyIndexes: file_techbridge_ap_metering_v1_outcome_proto_depIdxs,
		MessageInfos:      file_techbridge_ap_metering_v1_outcome_proto_msgTypes,
	}.Build()
	File_techbridge_ap_metering_v1_outcome_proto = out.File
	file_techbridge_ap_metering_v1_outcome_proto_goTypes = nil
	file_techbridge_ap_metering_v1_outcome_proto_depIdxs = nil
}
