// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: techbridge/ap/metering/v1/outcome.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-15 11:20:12 UTC

package metering

const (
	// OutcomesService_CreateOutcomeDefinition_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.CreateOutcomeDefinition method.
	OutcomesService_CreateOutcomeDefinition_FullMethodDescription = "Declares a kind of business outcome, e.g. a shortlist or a finished report."
	// OutcomesService_GetOutcomeDefinition_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.GetOutcomeDefinition method.
	OutcomesService_GetOutcomeDefinition_FullMethodDescription = "Returns a single outcome definition by resource name."
	// OutcomesService_UpdateOutcomeDefinition_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.UpdateOutcomeDefinition method.
	OutcomesService_UpdateOutcomeDefinition_FullMethodDescription = "Updates an outcome definition."
	// OutcomesService_ListOutcomeDefinitions_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.ListOutcomeDefinitions method.
	OutcomesService_ListOutcomeDefinitions_FullMethodDescription = "Lists the outcome definitions declared by an organisation."
	// OutcomesService_CreateOutcome_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.CreateOutcome method.
	OutcomesService_CreateOutcome_FullMethodDescription = "Records that a request produced some number of outcomes."
	// OutcomesService_ListOutcomes_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.ListOutcomes method.
	OutcomesService_ListOutcomes_FullMethodDescription = "Lists recorded outcomes."
)
