// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: techbridge/ap/metering/v1/outcome.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-03 14:32:42 UTC

package metering

const (
	// OutcomesService_CreateOutcomeDefinition_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.CreateOutcomeDefinition method.
	OutcomesService_CreateOutcomeDefinition_FullMethodDescription = ""
	// OutcomesService_GetOutcomeDefinition_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.GetOutcomeDefinition method.
	OutcomesService_GetOutcomeDefinition_FullMethodDescription = ""
	// OutcomesService_UpdateOutcomeDefinition_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.UpdateOutcomeDefinition method.
	OutcomesService_UpdateOutcomeDefinition_FullMethodDescription = ""
	// OutcomesService_ListOutcomeDefinitions_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.ListOutcomeDefinitions method.
	OutcomesService_ListOutcomeDefinitions_FullMethodDescription = ""
	// OutcomesService_CreateOutcome_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.CreateOutcome method.
	OutcomesService_CreateOutcome_FullMethodDescription = ""
	// OutcomesService_ListOutcomes_FullMethodDescription returns the description of the techbridge.ap.metering.v1.OutcomesService.ListOutcomes method.
	OutcomesService_ListOutcomes_FullMethodDescription = ""
)
