// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: techbridge/ap/metering/v1/outcome.proto

package metering

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutcomesService_CreateOutcomeDefinition_FullMethodName = "/techbridge.ap.metering.v1.OutcomesService/CreateOutcomeDefinition"
	OutcomesService_GetOutcomeDefinition_FullMethodName    = "/techbridge.ap.metering.v1.OutcomesService/GetOutcomeDefinition"
	OutcomesService_UpdateOutcomeDefinition_FullMethodName = "/techbridge.ap.metering.v1.OutcomesService/UpdateOutcomeDefinition"
	OutcomesService_ListOutcomeDefinitions_FullMethodName  = "/techbridge.ap.metering.v1.OutcomesService/ListOutcomeDefinitions"
	OutcomesService_CreateOutcome_FullMethodName           = "/techbridge.ap.metering.v1.OutcomesService/CreateOutcome"
	OutcomesService_ListOutcomes_FullMethodName            = "/techbridge.ap.metering.v1.OutcomesService/ListOutcomes"
)

// OutcomesServiceClient is the client API for OutcomesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OutcomesService records units of business work, so that cost can be
// expressed per outcome rather than per million tokens.
//
// An outcome attaches to a request, not to an individual activity. One request
// may make many model calls; the shortlist it produced is one outcome, and
// dividing the request's activities by the outcome gives the cost of producing
// it. Attaching the count to each activity instead would multiply it by however
// many model calls that run happened to make.
//
// Only the product knows what a unit of work is, which is why the definition is
// declared by the product rather than shipped with the service.
//
// Recorded outcomes are append-only, for the same reason activities are: a
// cost-per-outcome figure that can be edited after the fact is not evidence of
// anything. Definitions can be updated, since renaming what a unit is called
// does not change what was counted.
type OutcomesServiceClient interface {
	// Declares a kind of business outcome, e.g. a shortlist or a finished report.
	CreateOutcomeDefinition(ctx context.Context, in *CreateOutcomeDefinitionRequest, opts ...grpc.CallOption) (*OutcomeDefinition, error)
	// Returns a single outcome definition by resource name.
	GetOutcomeDefinition(ctx context.Context, in *GetOutcomeDefinitionRequest, opts ...grpc.CallOption) (*OutcomeDefinition, error)
	// Updates an outcome definition.
	UpdateOutcomeDefinition(ctx context.Context, in *UpdateOutcomeDefinitionRequest, opts ...grpc.CallOption) (*OutcomeDefinition, error)
	// Lists the outcome definitions declared by an organisation.
	ListOutcomeDefinitions(ctx context.Context, in *ListOutcomeDefinitionsRequest, opts ...grpc.CallOption) (*ListOutcomeDefinitionsResponse, error)
	// Records that a request produced some number of outcomes.
	CreateOutcome(ctx context.Context, in *CreateOutcomeRequest, opts ...grpc.CallOption) (*Outcome, error)
	// Lists recorded outcomes.
	ListOutcomes(ctx context.Context, in *ListOutcomesRequest, opts ...grpc.CallOption) (*ListOutcomesResponse, error)
}

type outcomesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutcomesServiceClient(cc grpc.ClientConnInterface) OutcomesServiceClient {
	return &outcomesServiceClient{cc}
}

func (c *outcomesServiceClient) CreateOutcomeDefinition(ctx context.Context, in *CreateOutcomeDefinitionRequest, opts ...grpc.CallOption) (*OutcomeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutcomeDefinition)
	err := c.cc.Invoke(ctx, OutcomesService_CreateOutcomeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outcomesServiceClient) GetOutcomeDefinition(ctx context.Context, in *GetOutcomeDefinitionRequest, opts ...grpc.CallOption) (*OutcomeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutcomeDefinition)
	err := c.cc.Invoke(ctx, OutcomesService_GetOutcomeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outcomesServiceClient) UpdateOutcomeDefinition(ctx context.Context, in *UpdateOutcomeDefinitionRequest, opts ...grpc.CallOption) (*OutcomeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutcomeDefinition)
	err := c.cc.Invoke(ctx, OutcomesService_UpdateOutcomeDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outcomesServiceClient) ListOutcomeDefinitions(ctx context.Context, in *ListOutcomeDefinitionsRequest, opts ...grpc.CallOption) (*ListOutcomeDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOutcomeDefinitionsResponse)
	err := c.cc.Invoke(ctx, OutcomesService_ListOutcomeDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outcomesServiceClient) CreateOutcome(ctx context.Context, in *CreateOutcomeRequest, opts ...grpc.CallOption) (*Outcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Outcome)
	err := c.cc.Invoke(ctx, OutcomesService_CreateOutcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outcomesServiceClient) ListOutcomes(ctx context.Context, in *ListOutcomesRequest, opts ...grpc.CallOption) (*ListOutcomesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOutcomesResponse)
	err := c.cc.Invoke(ctx, OutcomesService_ListOutcomes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutcomesServiceServer is the server API for OutcomesService service.
// All implementations must embed UnimplementedOutcomesServiceServer
// for forward compatibility.
//
// OutcomesService records units of business work, so that cost can be
// expressed per outcome rather than per million tokens.
//
// An outcome attaches to a request, not to an individual activity. One request
// may make many model calls; the shortlist it produced is one outcome, and
// dividing the request's activities by the outcome gives the cost of producing
// it. Attaching the count to each activity instead would multiply it by however
// many model calls that run happened to make.
//
// Only the product knows what a unit of work is, which is why the definition is
// declared by the product rather than shipped with the service.
//
// Recorded outcomes are append-only, for the same reason activities are: a
// cost-per-outcome figure that can be edited after the fact is not evidence of
// anything. Definitions can be updated, since renaming what a unit is called
// does not change what was counted.
type OutcomesServiceServer interface {
	// Declares a kind of business outcome, e.g. a shortlist or a finished report.
	CreateOutcomeDefinition(context.Context, *CreateOutcomeDefinitionRequest) (*OutcomeDefinition, error)
	// Returns a single outcome definition by resource name.
	GetOutcomeDefinition(context.Context, *GetOutcomeDefinitionRequest) (*OutcomeDefinition, error)
	// Updates an outcome definition.
	UpdateOutcomeDefinition(context.Context, *UpdateOutcomeDefinitionRequest) (*OutcomeDefinition, error)
	// Lists the outcome definitions declared by an organisation.
	ListOutcomeDefinitions(context.Context, *ListOutcomeDefinitionsRequest) (*ListOutcomeDefinitionsResponse, error)
	// Records that a request produced some number of outcomes.
	CreateOutcome(context.Context, *CreateOutcomeRequest) (*Outcome, error)
	// Lists recorded outcomes.
	ListOutcomes(context.Context, *ListOutcomesRequest) (*ListOutcomesResponse, error)
	mustEmbedUnimplementedOutcomesServiceServer()
}

// UnimplementedOutcomesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutcomesServiceServer struct{}

func (UnimplementedOutcomesServiceServer) CreateOutcomeDefinition(context.Context, *CreateOutcomeDefinitionRequest) (*OutcomeDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOutcomeDefinition not implemented")
}
func (UnimplementedOutcomesServiceServer) GetOutcomeDefinition(context.Context, *GetOutcomeDefinitionRequest) (*OutcomeDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOutcomeDefinition not implemented")
}
func (UnimplementedOutcomesServiceServer) UpdateOutcomeDefinition(context.Context, *UpdateOutcomeDefinitionRequest) (*OutcomeDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOutcomeDefinition not implemented")
}
func (UnimplementedOutcomesServiceServer) ListOutcomeDefinitions(context.Context, *ListOutcomeDefinitionsRequest) (*ListOutcomeDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOutcomeDefinitions not implemented")
}
func (UnimplementedOutcomesServiceServer) CreateOutcome(context.Context, *CreateOutcomeRequest) (*Outcome, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOutcome not implemented")
}
func (UnimplementedOutcomesServiceServer) ListOutcomes(context.Context, *ListOutcomesRequest) (*ListOutcomesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOutcomes not implemented")
}
func (UnimplementedOutcomesServiceServer) mustEmbedUnimplementedOutcomesServiceServer() {}
func (UnimplementedOutcomesServiceServer) testEmbeddedByValue()                         {}

// UnsafeOutcomesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutcomesServiceServer will
// result in compilation errors.
type UnsafeOutcomesServiceServer interface {
	mustEmbedUnimplementedOutcomesServiceServer()
}

func RegisterOutcomesServiceServer(s grpc.ServiceRegistrar, srv OutcomesServiceServer) {
	// If the following call panics, it indicates UnimplementedOutcomesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutcomesService_ServiceDesc, srv)
}

func _OutcomesService_CreateOutcomeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOutcomeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutcomesServiceServer).CreateOutcomeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutcomesService_CreateOutcomeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutcomesServiceServer).CreateOutcomeDefinition(ctx, req.(*CreateOutcomeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutcomesService_GetOutcomeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOutcomeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutcomesServiceServer).GetOutcomeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutcomesService_GetOutcomeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutcomesServiceServer).GetOutcomeDefinition(ctx, req.(*GetOutcomeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutcomesService_UpdateOutcomeDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOutcomeDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutcomesServiceServer).UpdateOutcomeDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutcomesService_UpdateOutcomeDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutcomesServiceServer).UpdateOutcomeDefinition(ctx, req.(*UpdateOutcomeDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutcomesService_ListOutcomeDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOutcomeDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutcomesServiceServer).ListOutcomeDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutcomesService_ListOutcomeDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutcomesServiceServer).ListOutcomeDefinitions(ctx, req.(*ListOutcomeDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutcomesService_CreateOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOutcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutcomesServiceServer).CreateOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutcomesService_CreateOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutcomesServiceServer).CreateOutcome(ctx, req.(*CreateOutcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutcomesService_ListOutcomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOutcomesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutcomesServiceServer).ListOutcomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutcomesService_ListOutcomes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutcomesServiceServer).ListOutcomes(ctx, req.(*ListOutcomesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutcomesService_ServiceDesc is the grpc.ServiceDesc for OutcomesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutcomesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "techbridge.ap.metering.v1.OutcomesService",
	HandlerType: (*OutcomesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOutcomeDefinition",
			Handler:    _OutcomesService_CreateOutcomeDefinition_Handler,
		},
		{
			MethodName: "GetOutcomeDefinition",
			Handler:    _OutcomesService_GetOutcomeDefinition_Handler,
		},
		{
			MethodName: "UpdateOutcomeDefinition",
			Handler:    _OutcomesService_UpdateOutcomeDefinition_Handler,
		},
		{
			MethodName: "ListOutcomeDefinitions",
			Handler:    _OutcomesService_ListOutcomeDefinitions_Handler,
		},
		{
			MethodName: "CreateOutcome",
			Handler:    _OutcomesService_CreateOutcome_Handler,
		},
		{
			MethodName: "ListOutcomes",
			Handler:    _OutcomesService_ListOutcomes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "techbridge/ap/metering/v1/outcome.proto",
}
