// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: techbridge/ap/metering/v1/priceable_unit.proto

package metering

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What a rate is charged against.
type PriceableUnit_Kind int32

const (
	// Kind not specified.
	PriceableUnit_KIND_UNSPECIFIED PriceableUnit_Kind = 0
	// Tokens in the prompt.
	PriceableUnit_PROMPT_TOKENS PriceableUnit_Kind = 1
	// Tokens the model generated.
	PriceableUnit_CANDIDATE_TOKENS PriceableUnit_Kind = 2
	// Prompt tokens served from the provider's cache.
	PriceableUnit_CACHED_TOKENS PriceableUnit_Kind = 3
	// Prompt tokens written to the provider's cache.
	PriceableUnit_CACHE_WRITE_TOKENS PriceableUnit_Kind = 4
	// Tokens the model spent reasoning.
	PriceableUnit_REASONING_TOKENS PriceableUnit_Kind = 5
	// A whole request, e.g. one web search.
	PriceableUnit_REQUEST PriceableUnit_Kind = 6
)

// Enum value maps for PriceableUnit_Kind.
var (
	PriceableUnit_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "PROMPT_TOKENS",
		2: "CANDIDATE_TOKENS",
		3: "CACHED_TOKENS",
		4: "CACHE_WRITE_TOKENS",
		5: "REASONING_TOKENS",
		6: "REQUEST",
	}
	PriceableUnit_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":   0,
		"PROMPT_TOKENS":      1,
		"CANDIDATE_TOKENS":   2,
		"CACHED_TOKENS":      3,
		"CACHE_WRITE_TOKENS": 4,
		"REASONING_TOKENS":   5,
		"REQUEST":            6,
	}
)

func (x PriceableUnit_Kind) Enum() *PriceableUnit_Kind {
	p := new(PriceableUnit_Kind)
	*p = x
	return p
}

func (x PriceableUnit_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceableUnit_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_techbridge_ap_metering_v1_priceable_unit_proto_enumTypes[0].Descriptor()
}

func (PriceableUnit_Kind) Type() protoreflect.EnumType {
	return &file_techbridge_ap_metering_v1_priceable_unit_proto_enumTypes[0]
}

func (x PriceableUnit_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceableUnit_Kind.Descriptor instead.
func (PriceableUnit_Kind) EnumDescriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescGZIP(), []int{0, 0}
}

// One line of the rate card.
type PriceableUnit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the priceable unit.
	// Format: `priceableUnits/{priceable_unit}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable name, e.g. `Gemini 2.5 Pro output tokens`.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The provider that charges for it.
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// The model this rate applies to, where the charge is per model. Empty for a
	// charge that is not model-specific, such as a web search.
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// What is being counted.
	Kind PriceableUnit_Kind `protobuf:"varint,5,opt,name=kind,proto3,enum=techbridge.ap.metering.v1.PriceableUnit_Kind" json:"kind,omitempty"`
	// Deprecated: too coarse to hold a real rate. Use `unit_cost_nanos`.
	//
	// A single token often costs a fraction of one millionth of a dollar —
	// Gemini input is 1.25 millionths — so a whole number of millionths cannot
	// express it and rounds every such rate down. Left in place rather than
	// removed, and never read.
	//
	// Deprecated: Marked as deprecated in techbridge/ap/metering/v1/priceable_unit.proto.
	UnitCostMicros int64 `protobuf:"varint,6,opt,name=unit_cost_micros,json=unitCostMicros,proto3" json:"unit_cost_micros,omitempty"`
	// Cost of one unit, in billionths of a US dollar.
	//
	// Billionths rather than millionths because a per-token rate is routinely a
	// fraction of a millionth, and rounding one to a whole millionth undercounts
	// every token priced against it. An activity's cost is still stored in
	// millionths; the extra precision belongs to the rate, not to the money.
	UnitCostNanos int64 `protobuf:"varint,11,opt,name=unit_cost_nanos,json=unitCostNanos,proto3" json:"unit_cost_nanos,omitempty"`
	// When this rate takes effect, inclusive.
	EffectiveFrom *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	// When this rate stops applying, exclusive. Empty while it is current.
	EffectiveTo *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=effective_to,json=effectiveTo,proto3" json:"effective_to,omitempty"`
	// The rate card version this belongs to, recorded on every activity priced
	// with it, e.g. `2026-09`.
	RateCardVersion string `protobuf:"bytes,9,opt,name=rate_card_version,json=rateCardVersion,proto3" json:"rate_card_version,omitempty"`
	// Where the rate came from, e.g. a link to the provider's public price list.
	// Kept so a figure can be traced back to a published price.
	Source string `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	// Entity tag.
	Etag string `protobuf:"bytes,97,opt,name=etag,proto3" json:"etag,omitempty"`
	// When this rate was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When this rate was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceableUnit) Reset() {
	*x = PriceableUnit{}
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceableUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceableUnit) ProtoMessage() {}

func (x *PriceableUnit) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceableUnit.ProtoReflect.Descriptor instead.
func (*PriceableUnit) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescGZIP(), []int{0}
}

func (x *PriceableUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PriceableUnit) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PriceableUnit) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PriceableUnit) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PriceableUnit) GetKind() PriceableUnit_Kind {
	if x != nil {
		return x.Kind
	}
	return PriceableUnit_KIND_UNSPECIFIED
}

// Deprecated: Marked as deprecated in techbridge/ap/metering/v1/priceable_unit.proto.
func (x *PriceableUnit) GetUnitCostMicros() int64 {
	if x != nil {
		return x.UnitCostMicros
	}
	return 0
}

func (x *PriceableUnit) GetUnitCostNanos() int64 {
	if x != nil {
		return x.UnitCostNanos
	}
	return 0
}

func (x *PriceableUnit) GetEffectiveFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveFrom
	}
	return nil
}

func (x *PriceableUnit) GetEffectiveTo() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveTo
	}
	return nil
}

func (x *PriceableUnit) GetRateCardVersion() string {
	if x != nil {
		return x.RateCardVersion
	}
	return ""
}

func (x *PriceableUnit) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PriceableUnit) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *PriceableUnit) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *PriceableUnit) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Request for [PriceableUnitsService.CreatePriceableUnit].
type CreatePriceableUnitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The priceable unit to create.
	PriceableUnit *PriceableUnit `protobuf:"bytes,1,opt,name=priceable_unit,json=priceableUnit,proto3" json:"priceable_unit,omitempty"`
	// Optional caller-chosen identifier, used as the last segment of the
	// resource name. Assigned by the server when omitted.
	PriceableUnitId string `protobuf:"bytes,2,opt,name=priceable_unit_id,json=priceableUnitId,proto3" json:"priceable_unit_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePriceableUnitRequest) Reset() {
	*x = CreatePriceableUnitRequest{}
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePriceableUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePriceableUnitRequest) ProtoMessage() {}

func (x *CreatePriceableUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePriceableUnitRequest.ProtoReflect.Descriptor instead.
func (*CreatePriceableUnitRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePriceableUnitRequest) GetPriceableUnit() *PriceableUnit {
	if x != nil {
		return x.PriceableUnit
	}
	return nil
}

func (x *CreatePriceableUnitRequest) GetPriceableUnitId() string {
	if x != nil {
		return x.PriceableUnitId
	}
	return ""
}

// Request for [PriceableUnitsService.GetPriceableUnit].
type GetPriceableUnitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the priceable unit to retrieve.
	// Format: `priceableUnits/{priceable_unit}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceableUnitRequest) Reset() {
	*x = GetPriceableUnitRequest{}
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceableUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceableUnitRequest) ProtoMessage() {}

func (x *GetPriceableUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceableUnitRequest.ProtoReflect.Descriptor instead.
func (*GetPriceableUnitRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescGZIP(), []int{2}
}

func (x *GetPriceableUnitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request for [PriceableUnitsService.UpdatePriceableUnit].
type UpdatePriceableUnitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The priceable unit to update.
	PriceableUnit *PriceableUnit `protobuf:"bytes,1,opt,name=priceable_unit,json=priceableUnit,proto3" json:"priceable_unit,omitempty"`
	// The fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePriceableUnitRequest) Reset() {
	*x = UpdatePriceableUnitRequest{}
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePriceableUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePriceableUnitRequest) ProtoMessage() {}

func (x *UpdatePriceableUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePriceableUnitRequest.ProtoReflect.Descriptor instead.
func (*UpdatePriceableUnitRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePriceableUnitRequest) GetPriceableUnit() *PriceableUnit {
	if x != nil {
		return x.PriceableUnit
	}
	return nil
}

func (x *UpdatePriceableUnitRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request for [PriceableUnitsService.ListPriceableUnits].
type ListPriceableUnitsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum priceable units to return. Defaults to `100`, capped at `1000`.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token from a previous response, to retrieve the next page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional filter over the fields of `PriceableUnit`, e.g.
	// `provider = "VERTEX_AI" AND kind = CANDIDATE_TOKENS`.
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPriceableUnitsRequest) Reset() {
	*x = ListPriceableUnitsRequest{}
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPriceableUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPriceableUnitsRequest) ProtoMessage() {}

func (x *ListPriceableUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPriceableUnitsRequest.ProtoReflect.Descriptor instead.
func (*ListPriceableUnitsRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescGZIP(), []int{4}
}

func (x *ListPriceableUnitsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPriceableUnitsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPriceableUnitsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Response for [PriceableUnitsService.ListPriceableUnits].
type ListPriceableUnitsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The priceable units in this page.
	PriceableUnits []*PriceableUnit `protobuf:"bytes,1,rep,name=priceable_units,json=priceableUnits,proto3" json:"priceable_units,omitempty"`
	// Token to retrieve the next page, empty when there are no more.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPriceableUnitsResponse) Reset() {
	*x = ListPriceableUnitsResponse{}
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPriceableUnitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPriceableUnitsResponse) ProtoMessage() {}

func (x *ListPriceableUnitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPriceableUnitsResponse.ProtoReflect.Descriptor instead.
func (*ListPriceableUnitsResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescGZIP(), []int{5}
}

func (x *ListPriceableUnitsResponse) GetPriceableUnits() []*PriceableUnit {
	if x != nil {
		return x.PriceableUnits
	}
	return nil
}

func (x *ListPriceableUnitsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_techbridge_ap_metering_v1_priceable_unit_proto protoreflect.FileDescriptor

const file_techbridge_ap_metering_v1_priceable_unit_proto_rawDesc = "" +
	"\n" +
	".techbridge/ap/metering/v1/priceable_unit.proto\x12\x19techbridge.ap.metering.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x06\n" +
	"\rPriceableUnit\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vdisplayName\x12 \n" +
	"\bprovider\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\bprovider\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12G\n" +
	"\x04kind\x18\x05 \x01(\x0e2-.techbridge.ap.metering.v1.PriceableUnit.KindB\x04\xe2A\x01\x02R\x04kind\x12,\n" +
	"\x10unit_cost_micros\x18\x06 \x01(\x03B\x02\x18\x01R\x0eunitCostMicros\x12,\n" +
	"\x0funit_cost_nanos\x18\v \x01(\x03B\x04\xe2A\x01\x02R\runitCostNanos\x12G\n" +
	"\x0eeffective_from\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x02R\reffectiveFrom\x12=\n" +
	"\feffective_to\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\veffectiveTo\x120\n" +
	"\x11rate_card_version\x18\t \x01(\tB\x04\xe2A\x01\x02R\x0frateCardVersion\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12\x18\n" +
	"\x04etag\x18a \x01(\tB\x04\xe2A\x01\x03R\x04etag\x12A\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime\"\x93\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPROMPT_TOKENS\x10\x01\x12\x14\n" +
	"\x10CANDIDATE_TOKENS\x10\x02\x12\x11\n" +
	"\rCACHED_TOKENS\x10\x03\x12\x16\n" +
	"\x12CACHE_WRITE_TOKENS\x10\x04\x12\x14\n" +
	"\x10REASONING_TOKENS\x10\x05\x12\v\n" +
	"\aREQUEST\x10\x06:J\xeaAG\n" +
	"$metering.ap.techbridge/PriceableUnit\x12\x1fpriceableUnits/{priceable_unit}\"\x9f\x01\n" +
	"\x1aCreatePriceableUnitRequest\x12U\n" +
	"\x0epriceable_unit\x18\x01 \x01(\v2(.techbridge.ap.metering.v1.PriceableUnitB\x04\xe2A\x01\x02R\rpriceableUnit\x12*\n" +
	"\x11priceable_unit_id\x18\x02 \x01(\tR\x0fpriceableUnitId\"3\n" +
	"\x17GetPriceableUnitRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\"\xb0\x01\n" +
	"\x1aUpdatePriceableUnitRequest\x12U\n" +
	"\x0epriceable_unit\x18\x01 \x01(\v2(.techbridge.ap.metering.v1.PriceableUnitB\x04\xe2A\x01\x02R\rpriceableUnit\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"o\n" +
	"\x19ListPriceableUnitsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x97\x01\n" +
	"\x1aListPriceableUnitsResponse\x12Q\n" +
	"\x0fpriceable_units\x18\x01 \x03(\v2(.techbridge.ap.metering.v1.PriceableUnitR\x0epriceableUnits\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x85\x04\n" +
	"\x15PriceableUnitsService\x12x\n" +
	"\x13CreatePriceableUnit\x125.techbridge.ap.metering.v1.CreatePriceableUnitRequest\x1a(.techbridge.ap.metering.v1.PriceableUnit\"\x00\x12r\n" +
	"\x10GetPriceableUnit\x122.techbridge.ap.metering.v1.GetPriceableUnitRequest\x1a(.techbridge.ap.metering.v1.PriceableUnit\"\x00\x12x\n" +
	"\x13UpdatePriceableUnit\x125.techbridge.ap.metering.v1.UpdatePriceableUnitRequest\x1a(.techbridge.ap.metering.v1.PriceableUnit\"\x00\x12\x83\x01\n" +
	"\x12ListPriceableUnits\x124.techbridge.ap.metering.v1.ListPriceableUnitsRequest\x1a5.techbridge.ap.metering.v1.ListPriceableUnitsResponse\"\x00B#Z!alis.build/techbridge/ap/meteringb\x06proto3"

var (
	file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescOnce sync.Once
	file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescData []byte
)

func file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescGZIP() []byte {
	file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescOnce.Do(func() {
		file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_priceable_unit_proto_rawDesc), len(file_techbridge_ap_metering_v1_priceable_unit_proto_rawDesc)))
	})
	return file_techbridge_ap_metering_v1_priceable_unit_proto_rawDescData
}

var file_techbridge_ap_metering_v1_priceable_unit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_techbridge_ap_metering_v1_priceable_unit_proto_goTypes = []any{
	(PriceableUnit_Kind)(0),            // 0: techbridge.ap.metering.v1.PriceableUnit.Kind
	(*PriceableUnit)(nil),              // 1: techbridge.ap.metering.v1.PriceableUnit
	(*CreatePriceableUnitRequest)(nil), // 2: techbridge.ap.metering.v1.CreatePriceableUnitRequest
	(*GetPriceableUnitRequest)(nil),    // 3: techbridge.ap.metering.v1.GetPriceableUnitRequest
	(*UpdatePriceableUnitRequest)(nil), // 4: techbridge.ap.metering.v1.UpdatePriceableUnitRequest
	(*ListPriceableUnitsRequest)(nil),  // 5: techbridge.ap.metering.v1.ListPriceableUnitsRequest
	(*ListPriceableUnitsResponse)(nil), // 6: techbridge.ap.metering.v1.ListPriceableUnitsResponse
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),      // 8: google.protobuf.FieldMask
}
var file_techbridge_ap_metering_v1_priceable_unit_proto_depIdxs = []int32{
	0,  // 0: techbridge.ap.metering.v1.PriceableUnit.kind:type_name -> techbridge.ap.metering.v1.PriceableUnit.Kind
	7,  // 1: techbridge.ap.metering.v1.PriceableUnit.effective_from:type_name -> google.protobuf.Timestamp
	7,  // 2: techbridge.ap.metering.v1.PriceableUnit.effective_to:type_name -> google.protobuf.Timestamp
	7,  // 3: techbridge.ap.metering.v1.PriceableUnit.create_time:type_name -> google.protobuf.Timestamp
	7,  // 4: techbridge.ap.metering.v1.PriceableUnit.update_time:type_name -> google.protobuf.Timestamp
	1,  // 5: techbridge.ap.metering.v1.CreatePriceableUnitRequest.priceable_unit:type_name -> techbridge.ap.metering.v1.PriceableUnit
	1,  // 6: techbridge.ap.metering.v1.UpdatePriceableUnitRequest.priceable_unit:type_name -> techbridge.ap.metering.v1.PriceableUnit
	8,  // 7: techbridge.ap.metering.v1.UpdatePriceableUnitRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 8: techbridge.ap.metering.v1.ListPriceableUnitsResponse.priceable_units:type_name -> techbridge.ap.metering.v1.PriceableUnit
	2,  // 9: techbridge.ap.metering.v1.PriceableUnitsService.CreatePriceableUnit:input_type -> techbridge.ap.metering.v1.CreatePriceableUnitRequest
	3,  // 10: techbridge.ap.metering.v1.PriceableUnitsService.GetPriceableUnit:input_type -> techbridge.ap.metering.v1.GetPriceableUnitRequest
	4,  // 11: techbridge.ap.metering.v1.PriceableUnitsService.UpdatePriceableUnit:input_type -> techbridge.ap.metering.v1.UpdatePriceableUnitRequest
	5,  // 12: techbridge.ap.metering.v1.PriceableUnitsService.ListPriceableUnits:input_type -> techbridge.ap.metering.v1.ListPriceableUnitsRequest
	1,  // 13: techbridge.ap.metering.v1.PriceableUnitsService.CreatePriceableUnit:output_type -> techbridge.ap.metering.v1.PriceableUnit
	1,  // 14: techbridge.ap.metering.v1.PriceableUnitsService.GetPriceableUnit:output_type -> techbridge.ap.metering.v1.PriceableUnit
	1,  // 15: techbridge.ap.metering.v1.PriceableUnitsService.UpdatePriceableUnit:output_type -> techbridge.ap.metering.v1.PriceableUnit
	6,  // 16: techbridge.ap.metering.v1.PriceableUnitsService.ListPriceableUnits:output_type -> techbridge.ap.metering.v1.ListPriceableUnitsResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_techbridge_ap_metering_v1_priceable_unit_proto_init() }
func file_techbridge_ap_metering_v1_priceable_unit_proto_init() {
	if File_techbridge_ap_metering_v1_priceable_unit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_priceable_unit_proto_rawDesc), len(file_techbridge_ap_metering_v1_priceable_unit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techbridge_ap_metering_v1_priceable_unit_proto_goTypes,
		DependencyIndexes: file_techbridge_ap_metering_v1_priceable_unit_proto_depIdxs,
		EnumInfos:         file_techbridge_ap_metering_v1_priceable_unit_proto_enumTypes,
		MessageInfos:      file_techbridge_ap_metering_v1_priceable_unit_proto_msgTypes,
	}.Build()
	File_techbridge_ap_metering_v1_priceable_unit_proto = out.File
	file_techbridge_ap_metering_v1_priceable_unit_proto_goTypes = nil
	file_techbridge_ap_metering_v1_priceable_unit_proto_depIdxs = nil
}
