// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: techbridge/ap/metering/v1/priceable_unit.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-25 14:38:50 UTC

package metering

const (
	// PriceableUnitsService_CreatePriceableUnit_FullMethodDescription returns the description of the techbridge.ap.metering.v1.PriceableUnitsService.CreatePriceableUnit method.
	PriceableUnitsService_CreatePriceableUnit_FullMethodDescription = "Adds a rate to the rate card."
	// PriceableUnitsService_GetPriceableUnit_FullMethodDescription returns the description of the techbridge.ap.metering.v1.PriceableUnitsService.GetPriceableUnit method.
	PriceableUnitsService_GetPriceableUnit_FullMethodDescription = "Returns a single priceable unit by resource name."
	// PriceableUnitsService_UpdatePriceableUnit_FullMethodDescription returns the description of the techbridge.ap.metering.v1.PriceableUnitsService.UpdatePriceableUnit method.
	PriceableUnitsService_UpdatePriceableUnit_FullMethodDescription = "Updates a priceable unit. Correcting a mistake is the intended use;\n a price change should be a new unit with a later `effective_from`."
	// PriceableUnitsService_ListPriceableUnits_FullMethodDescription returns the description of the techbridge.ap.metering.v1.PriceableUnitsService.ListPriceableUnits method.
	PriceableUnitsService_ListPriceableUnits_FullMethodDescription = "Lists the rate card."
)
