// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: techbridge/ap/metering/v1/priceable_unit.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-03 14:32:42 UTC

package metering

const (
	// PriceableUnitsService_CreatePriceableUnit_FullMethodDescription returns the description of the techbridge.ap.metering.v1.PriceableUnitsService.CreatePriceableUnit method.
	PriceableUnitsService_CreatePriceableUnit_FullMethodDescription = ""
	// PriceableUnitsService_GetPriceableUnit_FullMethodDescription returns the description of the techbridge.ap.metering.v1.PriceableUnitsService.GetPriceableUnit method.
	PriceableUnitsService_GetPriceableUnit_FullMethodDescription = ""
	// PriceableUnitsService_UpdatePriceableUnit_FullMethodDescription returns the description of the techbridge.ap.metering.v1.PriceableUnitsService.UpdatePriceableUnit method.
	PriceableUnitsService_UpdatePriceableUnit_FullMethodDescription = ""
	// PriceableUnitsService_ListPriceableUnits_FullMethodDescription returns the description of the techbridge.ap.metering.v1.PriceableUnitsService.ListPriceableUnits method.
	PriceableUnitsService_ListPriceableUnits_FullMethodDescription = ""
)
