// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: techbridge/ap/metering/v1/priceable_unit.proto

package metering

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceableUnitsService_CreatePriceableUnit_FullMethodName = "/techbridge.ap.metering.v1.PriceableUnitsService/CreatePriceableUnit"
	PriceableUnitsService_GetPriceableUnit_FullMethodName    = "/techbridge.ap.metering.v1.PriceableUnitsService/GetPriceableUnit"
	PriceableUnitsService_UpdatePriceableUnit_FullMethodName = "/techbridge.ap.metering.v1.PriceableUnitsService/UpdatePriceableUnit"
	PriceableUnitsService_ListPriceableUnits_FullMethodName  = "/techbridge.ap.metering.v1.PriceableUnitsService/ListPriceableUnits"
)

// PriceableUnitsServiceClient is the client API for PriceableUnitsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PriceableUnitsService holds the rate card: what each billable thing costs.
//
// Rates are not organisation-specific, so priceable units sit outside the
// organisation hierarchy. Each carries the window it applies to, and pricing an
// activity uses the rate in force when the work happened. That way a provider
// raising a price does not silently rewrite what last month cost.
type PriceableUnitsServiceClient interface {
	// Adds a rate to the rate card.
	CreatePriceableUnit(ctx context.Context, in *CreatePriceableUnitRequest, opts ...grpc.CallOption) (*PriceableUnit, error)
	// Returns a single priceable unit by resource name.
	GetPriceableUnit(ctx context.Context, in *GetPriceableUnitRequest, opts ...grpc.CallOption) (*PriceableUnit, error)
	// Updates a priceable unit. Correcting a mistake is the intended use;
	// a price change should be a new unit with a later `effective_from`.
	UpdatePriceableUnit(ctx context.Context, in *UpdatePriceableUnitRequest, opts ...grpc.CallOption) (*PriceableUnit, error)
	// Lists the rate card.
	ListPriceableUnits(ctx context.Context, in *ListPriceableUnitsRequest, opts ...grpc.CallOption) (*ListPriceableUnitsResponse, error)
}

type priceableUnitsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceableUnitsServiceClient(cc grpc.ClientConnInterface) PriceableUnitsServiceClient {
	return &priceableUnitsServiceClient{cc}
}

func (c *priceableUnitsServiceClient) CreatePriceableUnit(ctx context.Context, in *CreatePriceableUnitRequest, opts ...grpc.CallOption) (*PriceableUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceableUnit)
	err := c.cc.Invoke(ctx, PriceableUnitsService_CreatePriceableUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceableUnitsServiceClient) GetPriceableUnit(ctx context.Context, in *GetPriceableUnitRequest, opts ...grpc.CallOption) (*PriceableUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceableUnit)
	err := c.cc.Invoke(ctx, PriceableUnitsService_GetPriceableUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceableUnitsServiceClient) UpdatePriceableUnit(ctx context.Context, in *UpdatePriceableUnitRequest, opts ...grpc.CallOption) (*PriceableUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PriceableUnit)
	err := c.cc.Invoke(ctx, PriceableUnitsService_UpdatePriceableUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *priceableUnitsServiceClient) ListPriceableUnits(ctx context.Context, in *ListPriceableUnitsRequest, opts ...grpc.CallOption) (*ListPriceableUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPriceableUnitsResponse)
	err := c.cc.Invoke(ctx, PriceableUnitsService_ListPriceableUnits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceableUnitsServiceServer is the server API for PriceableUnitsService service.
// All implementations must embed UnimplementedPriceableUnitsServiceServer
// for forward compatibility.
//
// PriceableUnitsService holds the rate card: what each billable thing costs.
//
// Rates are not organisation-specific, so priceable units sit outside the
// organisation hierarchy. Each carries the window it applies to, and pricing an
// activity uses the rate in force when the work happened. That way a provider
// raising a price does not silently rewrite what last month cost.
type PriceableUnitsServiceServer interface {
	// Adds a rate to the rate card.
	CreatePriceableUnit(context.Context, *CreatePriceableUnitRequest) (*PriceableUnit, error)
	// Returns a single priceable unit by resource name.
	GetPriceableUnit(context.Context, *GetPriceableUnitRequest) (*PriceableUnit, error)
	// Updates a priceable unit. Correcting a mistake is the intended use;
	// a price change should be a new unit with a later `effective_from`.
	UpdatePriceableUnit(context.Context, *UpdatePriceableUnitRequest) (*PriceableUnit, error)
	// Lists the rate card.
	ListPriceableUnits(context.Context, *ListPriceableUnitsRequest) (*ListPriceableUnitsResponse, error)
	mustEmbedUnimplementedPriceableUnitsServiceServer()
}

// UnimplementedPriceableUnitsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceableUnitsServiceServer struct{}

func (UnimplementedPriceableUnitsServiceServer) CreatePriceableUnit(context.Context, *CreatePriceableUnitRequest) (*PriceableUnit, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePriceableUnit not implemented")
}
func (UnimplementedPriceableUnitsServiceServer) GetPriceableUnit(context.Context, *GetPriceableUnitRequest) (*PriceableUnit, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPriceableUnit not implemented")
}
func (UnimplementedPriceableUnitsServiceServer) UpdatePriceableUnit(context.Context, *UpdatePriceableUnitRequest) (*PriceableUnit, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePriceableUnit not implemented")
}
func (UnimplementedPriceableUnitsServiceServer) ListPriceableUnits(context.Context, *ListPriceableUnitsRequest) (*ListPriceableUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPriceableUnits not implemented")
}
func (UnimplementedPriceableUnitsServiceServer) mustEmbedUnimplementedPriceableUnitsServiceServer() {}
func (UnimplementedPriceableUnitsServiceServer) testEmbeddedByValue()                               {}

// UnsafePriceableUnitsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceableUnitsServiceServer will
// result in compilation errors.
type UnsafePriceableUnitsServiceServer interface {
	mustEmbedUnimplementedPriceableUnitsServiceServer()
}

func RegisterPriceableUnitsServiceServer(s grpc.ServiceRegistrar, srv PriceableUnitsServiceServer) {
	// If the following call panics, it indicates UnimplementedPriceableUnitsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceableUnitsService_ServiceDesc, srv)
}

func _PriceableUnitsService_CreatePriceableUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePriceableUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceableUnitsServiceServer).CreatePriceableUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceableUnitsService_CreatePriceableUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceableUnitsServiceServer).CreatePriceableUnit(ctx, req.(*CreatePriceableUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceableUnitsService_GetPriceableUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceableUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceableUnitsServiceServer).GetPriceableUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceableUnitsService_GetPriceableUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceableUnitsServiceServer).GetPriceableUnit(ctx, req.(*GetPriceableUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceableUnitsService_UpdatePriceableUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePriceableUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceableUnitsServiceServer).UpdatePriceableUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceableUnitsService_UpdatePriceableUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceableUnitsServiceServer).UpdatePriceableUnit(ctx, req.(*UpdatePriceableUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PriceableUnitsService_ListPriceableUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPriceableUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceableUnitsServiceServer).ListPriceableUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PriceableUnitsService_ListPriceableUnits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceableUnitsServiceServer).ListPriceableUnits(ctx, req.(*ListPriceableUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PriceableUnitsService_ServiceDesc is the grpc.ServiceDesc for PriceableUnitsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceableUnitsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "techbridge.ap.metering.v1.PriceableUnitsService",
	HandlerType: (*PriceableUnitsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePriceableUnit",
			Handler:    _PriceableUnitsService_CreatePriceableUnit_Handler,
		},
		{
			MethodName: "GetPriceableUnit",
			Handler:    _PriceableUnitsService_GetPriceableUnit_Handler,
		},
		{
			MethodName: "UpdatePriceableUnit",
			Handler:    _PriceableUnitsService_UpdatePriceableUnit_Handler,
		},
		{
			MethodName: "ListPriceableUnits",
			Handler:    _PriceableUnitsService_ListPriceableUnits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "techbridge/ap/metering/v1/priceable_unit.proto",
}
