// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: techbridge/ap/metering/v1/user.proto

package metering

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A person an organisation's agents do work for, named.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the user.
	// Format: `organisations/{organisation}/workspaces/{workspace}/users/{user}`
	//
	// The directory sits under the workspace because an identifier is only unique within the sign-in that issued it, and two tenants of the same organisation may each run their own. A person is looked up in the workspace their activities were recorded under, and nowhere else.
	//
	// `{user}` is the identifier exactly as the organisation's agents stamp it on `Activity.user`; that equality is the whole join. It is the bare identifier the organisation's sign-in issued, never an email, and it cannot contain `/`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The person's name as the organisation would show it, e.g. `Ada Lovelace`.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The person's email address, where the organisation chooses to send it.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// When this user was first named.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When this user was last written.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *User) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Request for [UsersService.GetUser].
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the user to retrieve.
	// Format: `organisations/{organisation}/workspaces/{workspace}/users/{user}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request for [UsersService.ListUsers].
type ListUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation, or the one workspace within it, whose users to list.
	// Format: `organisations/{organisation}` or `organisations/{organisation}/workspaces/{workspace}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Maximum users to return. Defaults to `100`, capped at `1000`.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token from a previous response, to retrieve the next page.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response for [UsersService.ListUsers].
type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The users in this page.
	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// Token to retrieve the next page, empty when there are no more.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request for [UsersService.BatchUpsertUsers].
type BatchUpsertUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The workspace the users belong to.
	// Format: `organisations/{organisation}/workspaces/{workspace}`
	//
	// An `organisations/{organisation}` on its own is accepted and writes into that organisation's default workspace, so a recorder written before workspaces existed keeps naming people correctly.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The users to write. Every `name` must sit under `parent`. Rejected as a whole if any one is invalid.
	Users         []*User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertUsersRequest) Reset() {
	*x = BatchUpsertUsersRequest{}
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertUsersRequest) ProtoMessage() {}

func (x *BatchUpsertUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchUpsertUsersRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *BatchUpsertUsersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchUpsertUsersRequest) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Response for [UsersService.BatchUpsertUsers].
type BatchUpsertUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The users as written.
	Users         []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertUsersResponse) Reset() {
	*x = BatchUpsertUsersResponse{}
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertUsersResponse) ProtoMessage() {}

func (x *BatchUpsertUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertUsersResponse.ProtoReflect.Descriptor instead.
func (*BatchUpsertUsersResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *BatchUpsertUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Request for [UsersService.DeleteUser].
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the user to delete.
	// Format: `organisations/{organisation}/workspaces/{workspace}/users/{user}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_metering_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_metering_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_techbridge_ap_metering_v1_user_proto protoreflect.FileDescriptor

const file_techbridge_ap_metering_v1_user_proto_rawDesc = "" +
	"\n" +
	"$techbridge/ap/metering/v1/user.proto\x12\x19techbridge.ap.metering.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x02\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12A\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime:b\xeaA_\n" +
	"\x1bmetering.ap.techbridge/User\x12@organisations/{organisation}/workspaces/{workspace}/users/{user}\"*\n" +
	"\x0eGetUserRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\"l\n" +
	"\x10ListUsersRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"r\n" +
	"\x11ListUsersResponse\x125\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.techbridge.ap.metering.v1.UserR\x05users\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"t\n" +
	"\x17BatchUpsertUsersRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12;\n" +
	"\x05users\x18\x02 \x03(\v2\x1f.techbridge.ap.metering.v1.UserB\x04\xe2A\x01\x02R\x05users\"Q\n" +
	"\x18BatchUpsertUsersResponse\x125\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.techbridge.ap.metering.v1.UserR\x05users\"-\n" +
	"\x11DeleteUserRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name2\x84\x04\n" +
	"\fUsersService\x12W\n" +
	"\aGetUser\x12).techbridge.ap.metering.v1.GetUserRequest\x1a\x1f.techbridge.ap.metering.v1.User\"\x00\x12\xc5\x01\n" +
	"\tListUsers\x12+.techbridge.ap.metering.v1.ListUsersRequest\x1a,.techbridge.ap.metering.v1.ListUsersResponse\"]\x82\xd3\xe4\x93\x02WZ1\x12//v1/{parent=organisations/*/workspaces/*}/users\x12\"/v1/{parent=organisations/*}/users\x12}\n" +
	"\x10BatchUpsertUsers\x122.techbridge.ap.metering.v1.BatchUpsertUsersRequest\x1a3.techbridge.ap.metering.v1.BatchUpsertUsersResponse\"\x00\x12T\n" +
	"\n" +
	"DeleteUser\x12,.techbridge.ap.metering.v1.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x00B#Z!alis.build/techbridge/ap/meteringb\x06proto3"

var (
	file_techbridge_ap_metering_v1_user_proto_rawDescOnce sync.Once
	file_techbridge_ap_metering_v1_user_proto_rawDescData []byte
)

func file_techbridge_ap_metering_v1_user_proto_rawDescGZIP() []byte {
	file_techbridge_ap_metering_v1_user_proto_rawDescOnce.Do(func() {
		file_techbridge_ap_metering_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_user_proto_rawDesc), len(file_techbridge_ap_metering_v1_user_proto_rawDesc)))
	})
	return file_techbridge_ap_metering_v1_user_proto_rawDescData
}

var file_techbridge_ap_metering_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_techbridge_ap_metering_v1_user_proto_goTypes = []any{
	(*User)(nil),                     // 0: techbridge.ap.metering.v1.User
	(*GetUserRequest)(nil),           // 1: techbridge.ap.metering.v1.GetUserRequest
	(*ListUsersRequest)(nil),         // 2: techbridge.ap.metering.v1.ListUsersRequest
	(*ListUsersResponse)(nil),        // 3: techbridge.ap.metering.v1.ListUsersResponse
	(*BatchUpsertUsersRequest)(nil),  // 4: techbridge.ap.metering.v1.BatchUpsertUsersRequest
	(*BatchUpsertUsersResponse)(nil), // 5: techbridge.ap.metering.v1.BatchUpsertUsersResponse
	(*DeleteUserRequest)(nil),        // 6: techbridge.ap.metering.v1.DeleteUserRequest
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 8: google.protobuf.Empty
}
var file_techbridge_ap_metering_v1_user_proto_depIdxs = []int32{
	7, // 0: techbridge.ap.metering.v1.User.create_time:type_name -> google.protobuf.Timestamp
	7, // 1: techbridge.ap.metering.v1.User.update_time:type_name -> google.protobuf.Timestamp
	0, // 2: techbridge.ap.metering.v1.ListUsersResponse.users:type_name -> techbridge.ap.metering.v1.User
	0, // 3: techbridge.ap.metering.v1.BatchUpsertUsersRequest.users:type_name -> techbridge.ap.metering.v1.User
	0, // 4: techbridge.ap.metering.v1.BatchUpsertUsersResponse.users:type_name -> techbridge.ap.metering.v1.User
	1, // 5: techbridge.ap.metering.v1.UsersService.GetUser:input_type -> techbridge.ap.metering.v1.GetUserRequest
	2, // 6: techbridge.ap.metering.v1.UsersService.ListUsers:input_type -> techbridge.ap.metering.v1.ListUsersRequest
	4, // 7: techbridge.ap.metering.v1.UsersService.BatchUpsertUsers:input_type -> techbridge.ap.metering.v1.BatchUpsertUsersRequest
	6, // 8: techbridge.ap.metering.v1.UsersService.DeleteUser:input_type -> techbridge.ap.metering.v1.DeleteUserRequest
	0, // 9: techbridge.ap.metering.v1.UsersService.GetUser:output_type -> techbridge.ap.metering.v1.User
	3, // 10: techbridge.ap.metering.v1.UsersService.ListUsers:output_type -> techbridge.ap.metering.v1.ListUsersResponse
	5, // 11: techbridge.ap.metering.v1.UsersService.BatchUpsertUsers:output_type -> techbridge.ap.metering.v1.BatchUpsertUsersResponse
	8, // 12: techbridge.ap.metering.v1.UsersService.DeleteUser:output_type -> google.protobuf.Empty
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_techbridge_ap_metering_v1_user_proto_init() }
func file_techbridge_ap_metering_v1_user_proto_init() {
	if File_techbridge_ap_metering_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_techbridge_ap_metering_v1_user_proto_rawDesc), len(file_techbridge_ap_metering_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techbridge_ap_metering_v1_user_proto_goTypes,
		DependencyIndexes: file_techbridge_ap_metering_v1_user_proto_depIdxs,
		MessageInfos:      file_techbridge_ap_metering_v1_user_proto_msgTypes,
	}.Build()
	File_techbridge_ap_metering_v1_user_proto = out.File
	file_techbridge_ap_metering_v1_user_proto_goTypes = nil
	file_techbridge_ap_metering_v1_user_proto_depIdxs = nil
}
