// Code generated by https://github.com/alis-exchange/protoc-gen-go-meta. DO NOT EDIT.
//
// Source: techbridge/ap/governance/v1/budget.proto
// Plugin version: v0.0.1
//
// Generated on: 2026-09-09 08:11:07 UTC

package governance

const (
	// BudgetsService_GetBudget_FullMethodDescription returns the description of the techbridge.ap.governance.v1.BudgetsService.GetBudget method.
	BudgetsService_GetBudget_FullMethodDescription = "Returns a single budget's configuration by resource name. Returns the ceiling and its scope, not current spend. How spend is\n tracked against a budget is not yet part of this contract."
	// BudgetsService_CreateBudget_FullMethodDescription returns the description of the techbridge.ap.governance.v1.BudgetsService.CreateBudget method.
	BudgetsService_CreateBudget_FullMethodDescription = "Registers a new budget. Rejects PERIOD_UNSPECIFIED and a scope combining user and agent."
	// BudgetsService_UpdateBudget_FullMethodDescription returns the description of the techbridge.ap.governance.v1.BudgetsService.UpdateBudget method.
	BudgetsService_UpdateBudget_FullMethodDescription = "Updates an existing budget's configuration. Subject to the same period and scope-combination rules as CreateBudget."
	// BudgetsService_ListBudgets_FullMethodDescription returns the description of the techbridge.ap.governance.v1.BudgetsService.ListBudgets method.
	BudgetsService_ListBudgets_FullMethodDescription = "Lists the budgets configured for an organisation."
	// BudgetsService_RecordSpend_FullMethodDescription returns the description of the techbridge.ap.governance.v1.BudgetsService.RecordSpend method.
	BudgetsService_RecordSpend_FullMethodDescription = "Records that amounts were spent, so governance can apply them to every\n budget each is in scope for. Called by metering, after it has already written the corresponding\n activities. `spend` is repeated so this works whether metering calls it\n once per activity or once per batch."
)
