// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: techbridge/ap/governance/v1/budget.proto

package governance

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How often this budget's spend accounting resets.
//
// There is no default period. PERIOD_UNSPECIFIED means this budget has
// not been configured with one — it is not an implicit lifetime budget,
// and anything that evaluates a budget's accounting state must treat an
// unconfigured period as an error, never fall back to summing spend with
// no window.
type Budget_Period int32

const (
	Budget_PERIOD_UNSPECIFIED Budget_Period = 0
	// Resets at the start of each calendar month, UTC. The window is
	// [first instant of the current UTC calendar month, first instant of
	// the next UTC calendar month) — half-open, matching how this
	// contract already windows time elsewhere (e.g.
	// AggregateActivitiesRequest.start_time/end_time).
	Budget_MONTHLY Budget_Period = 1
)

// Enum value maps for Budget_Period.
var (
	Budget_Period_name = map[int32]string{
		0: "PERIOD_UNSPECIFIED",
		1: "MONTHLY",
	}
	Budget_Period_value = map[string]int32{
		"PERIOD_UNSPECIFIED": 0,
		"MONTHLY":            1,
	}
)

func (x Budget_Period) Enum() *Budget_Period {
	p := new(Budget_Period)
	*p = x
	return p
}

func (x Budget_Period) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Budget_Period) Descriptor() protoreflect.EnumDescriptor {
	return file_techbridge_ap_governance_v1_budget_proto_enumTypes[0].Descriptor()
}

func (Budget_Period) Type() protoreflect.EnumType {
	return &file_techbridge_ap_governance_v1_budget_proto_enumTypes[0]
}

func (x Budget_Period) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Budget_Period.Descriptor instead.
func (Budget_Period) EnumDescriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{0, 0}
}

// A spend ceiling for an organisation, optionally narrowed by product,
// user, or agent.
type Budget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the budget.
	// Format: `organisations/{organisation}/budgets/{budget}`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable name, e.g. `Rezco monthly ceiling`.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Narrows this budget to one product, e.g. `rezco`, matching
	// `Agent.product` in metering — carried here directly rather than looked
	// up from the agent registry, since governance holds its own authoritative
	// state and does not read metering. Empty means this budget is not
	// narrowed to a product: it applies across the organisation, covering
	// every product in it.
	Product string `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	// Narrows this budget to one user, matching `Activity.user`. Empty means
	// this budget is not narrowed to a user.
	User string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// The ceiling, in millionths of a US dollar.
	LimitMicros int64 `protobuf:"varint,5,opt,name=limit_micros,json=limitMicros,proto3" json:"limit_micros,omitempty"`
	// Narrows this budget to one agent.
	// Format: `organisations/{organisation}/agents/{agent}`
	// Empty means this budget is not narrowed to an agent.
	Agent string `protobuf:"bytes,6,opt,name=agent,proto3" json:"agent,omitempty"`
	// The accounting period this budget resets on. Required: a budget
	// cannot be evaluated without one. MONTHLY is the only supported value
	// today; the enum stays open for DAILY/WEEKLY/ANNUAL/etc. later without
	// a breaking change.
	Period Budget_Period `protobuf:"varint,7,opt,name=period,proto3,enum=techbridge.ap.governance.v1.Budget_Period" json:"period,omitempty"`
	// Entity tag.
	Etag string `protobuf:"bytes,97,opt,name=etag,proto3" json:"etag,omitempty"`
	// When this budget was created.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When this budget was last updated.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{0}
}

func (x *Budget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Budget) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Budget) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Budget) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Budget) GetLimitMicros() int64 {
	if x != nil {
		return x.LimitMicros
	}
	return 0
}

func (x *Budget) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Budget) GetPeriod() Budget_Period {
	if x != nil {
		return x.Period
	}
	return Budget_PERIOD_UNSPECIFIED
}

func (x *Budget) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *Budget) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Budget) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Request for [BudgetsService.GetBudget].
type GetBudgetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the budget to retrieve.
	// Format: `organisations/{organisation}/budgets/{budget}`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetRequest) Reset() {
	*x = GetBudgetRequest{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetRequest) ProtoMessage() {}

func (x *GetBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{1}
}

func (x *GetBudgetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request for [BudgetsService.CreateBudget].
type CreateBudgetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation to create the budget under.
	// Format: `organisations/{organisation}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The budget to create.
	Budget *Budget `protobuf:"bytes,2,opt,name=budget,proto3" json:"budget,omitempty"`
	// Optional caller-chosen identifier for the budget, used as the last
	// segment of its resource name. Assigned by the server when omitted.
	BudgetId      string `protobuf:"bytes,3,opt,name=budget_id,json=budgetId,proto3" json:"budget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetRequest) Reset() {
	*x = CreateBudgetRequest{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetRequest) ProtoMessage() {}

func (x *CreateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetRequest.ProtoReflect.Descriptor instead.
func (*CreateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBudgetRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateBudgetRequest) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *CreateBudgetRequest) GetBudgetId() string {
	if x != nil {
		return x.BudgetId
	}
	return ""
}

// Request for [BudgetsService.UpdateBudget].
type UpdateBudgetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The budget to update. Its `name` identifies which one.
	Budget *Budget `protobuf:"bytes,1,opt,name=budget,proto3" json:"budget,omitempty"`
	// The fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBudgetRequest) Reset() {
	*x = UpdateBudgetRequest{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBudgetRequest) ProtoMessage() {}

func (x *UpdateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBudgetRequest.ProtoReflect.Descriptor instead.
func (*UpdateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBudgetRequest) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *UpdateBudgetRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request for [BudgetsService.ListBudgets].
type ListBudgetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation whose budgets to list.
	// Format: `organisations/{organisation}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Maximum budgets to return. Defaults to `100`, capped at `1000`.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token from a previous response, to retrieve the next page.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsRequest) Reset() {
	*x = ListBudgetsRequest{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsRequest) ProtoMessage() {}

func (x *ListBudgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsRequest.ProtoReflect.Descriptor instead.
func (*ListBudgetsRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{4}
}

func (x *ListBudgetsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListBudgetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBudgetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response for [BudgetsService.ListBudgets].
type ListBudgetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The budgets in this page.
	Budgets []*Budget `protobuf:"bytes,1,rep,name=budgets,proto3" json:"budgets,omitempty"`
	// Token to retrieve the next page, empty when there are no more.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsResponse) Reset() {
	*x = ListBudgetsResponse{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsResponse) ProtoMessage() {}

func (x *ListBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsResponse.ProtoReflect.Descriptor instead.
func (*ListBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{5}
}

func (x *ListBudgetsResponse) GetBudgets() []*Budget {
	if x != nil {
		return x.Budgets
	}
	return nil
}

func (x *ListBudgetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request for [BudgetsService.RecordSpend].
type RecordSpendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation the spend belongs to.
	// Format: `organisations/{organisation}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The amounts spent.
	Spend []*SpendEvent `protobuf:"bytes,2,rep,name=spend,proto3" json:"spend,omitempty"`
	// Optional caller-supplied identifier that makes the push idempotent, so a
	// retried call does not count the same spend twice.
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSpendRequest) Reset() {
	*x = RecordSpendRequest{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSpendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSpendRequest) ProtoMessage() {}

func (x *RecordSpendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSpendRequest.ProtoReflect.Descriptor instead.
func (*RecordSpendRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{6}
}

func (x *RecordSpendRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *RecordSpendRequest) GetSpend() []*SpendEvent {
	if x != nil {
		return x.Spend
	}
	return nil
}

func (x *RecordSpendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// One amount to apply against every budget it is in scope for.
type SpendEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The activity that generated this spend.
	// Format: `organisations/{organisation}/activities/{activity}`
	Activity string `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	// The agent that spent it.
	// Format: `organisations/{organisation}/agents/{agent}`
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	// The product the agent belongs to, matching `Agent.product`. Determines
	// which product budget this spend counts against.
	Product string `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	// The user it is attributed to, matching `Activity.user`. Empty where the
	// work is not attributed to a person.
	User string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// How much was spent, in millionths of a US dollar. Matches
	// `Activity.estimated_cost_micros` at the time it was pushed; governance
	// never re-prices anything.
	AmountMicros int64 `protobuf:"varint,5,opt,name=amount_micros,json=amountMicros,proto3" json:"amount_micros,omitempty"`
	// When the spend occurred, matching `Activity.occurred_at`.
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendEvent) Reset() {
	*x = SpendEvent{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendEvent) ProtoMessage() {}

func (x *SpendEvent) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendEvent.ProtoReflect.Descriptor instead.
func (*SpendEvent) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{7}
}

func (x *SpendEvent) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *SpendEvent) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SpendEvent) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *SpendEvent) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SpendEvent) GetAmountMicros() int64 {
	if x != nil {
		return x.AmountMicros
	}
	return 0
}

func (x *SpendEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// Response for [BudgetsService.RecordSpend].
type RecordSpendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSpendResponse) Reset() {
	*x = RecordSpendResponse{}
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSpendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSpendResponse) ProtoMessage() {}

func (x *RecordSpendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_budget_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSpendResponse.ProtoReflect.Descriptor instead.
func (*RecordSpendResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP(), []int{8}
}

var File_techbridge_ap_governance_v1_budget_proto protoreflect.FileDescriptor

const file_techbridge_ap_governance_v1_budget_proto_rawDesc = "" +
	"\n" +
	"(techbridge/ap/governance/v1/budget.proto\x12\x1btechbridge.ap.governance.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x04\n" +
	"\x06Budget\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vdisplayName\x12\x18\n" +
	"\aproduct\x18\x03 \x01(\tR\aproduct\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12'\n" +
	"\flimit_micros\x18\x05 \x01(\x03B\x04\xe2A\x01\x02R\vlimitMicros\x12\x14\n" +
	"\x05agent\x18\x06 \x01(\tR\x05agent\x12H\n" +
	"\x06period\x18\a \x01(\x0e2*.techbridge.ap.governance.v1.Budget.PeriodB\x04\xe2A\x01\x02R\x06period\x12\x18\n" +
	"\x04etag\x18a \x01(\tB\x04\xe2A\x01\x03R\x04etag\x12A\n" +
	"\vcreate_time\x18b \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"createTime\x12A\n" +
	"\vupdate_time\x18c \x01(\v2\x1a.google.protobuf.TimestampB\x04\xe2A\x01\x03R\n" +
	"updateTime\"-\n" +
	"\x06Period\x12\x16\n" +
	"\x12PERIOD_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMONTHLY\x10\x01:S\xeaAP\n" +
	"\x1fgovernance.ap.techbridge/Budget\x12-organisations/{organisation}/budgets/{budget}\",\n" +
	"\x10GetBudgetRequest\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\"\x93\x01\n" +
	"\x13CreateBudgetRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12A\n" +
	"\x06budget\x18\x02 \x01(\v2#.techbridge.ap.governance.v1.BudgetB\x04\xe2A\x01\x02R\x06budget\x12\x1b\n" +
	"\tbudget_id\x18\x03 \x01(\tR\bbudgetId\"\x9b\x01\n" +
	"\x13UpdateBudgetRequest\x12A\n" +
	"\x06budget\x18\x01 \x01(\v2#.techbridge.ap.governance.v1.BudgetB\x04\xe2A\x01\x02R\x06budget\x12A\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x04\xe2A\x01\x02R\n" +
	"updateMask\"n\n" +
	"\x12ListBudgetsRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"|\n" +
	"\x13ListBudgetsResponse\x12=\n" +
	"\abudgets\x18\x01 \x03(\v2#.techbridge.ap.governance.v1.BudgetR\abudgets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x96\x01\n" +
	"\x12RecordSpendRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12C\n" +
	"\x05spend\x18\x02 \x03(\v2'.techbridge.ap.governance.v1.SpendEventB\x04\xe2A\x01\x02R\x05spend\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\xe6\x01\n" +
	"\n" +
	"SpendEvent\x12 \n" +
	"\bactivity\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\bactivity\x12\x1a\n" +
	"\x05agent\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05agent\x12\x1e\n" +
	"\aproduct\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\aproduct\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12)\n" +
	"\ramount_micros\x18\x05 \x01(\x03B\x04\xe2A\x01\x02R\famountMicros\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\x15\n" +
	"\x13RecordSpendResponse2\xad\x04\n" +
	"\x0eBudgetsService\x12a\n" +
	"\tGetBudget\x12-.techbridge.ap.governance.v1.GetBudgetRequest\x1a#.techbridge.ap.governance.v1.Budget\"\x00\x12g\n" +
	"\fCreateBudget\x120.techbridge.ap.governance.v1.CreateBudgetRequest\x1a#.techbridge.ap.governance.v1.Budget\"\x00\x12g\n" +
	"\fUpdateBudget\x120.techbridge.ap.governance.v1.UpdateBudgetRequest\x1a#.techbridge.ap.governance.v1.Budget\"\x00\x12r\n" +
	"\vListBudgets\x12/.techbridge.ap.governance.v1.ListBudgetsRequest\x1a0.techbridge.ap.governance.v1.ListBudgetsResponse\"\x00\x12r\n" +
	"\vRecordSpend\x12/.techbridge.ap.governance.v1.RecordSpendRequest\x1a0.techbridge.ap.governance.v1.RecordSpendResponse\"\x00B%Z#alis.build/techbridge/ap/governanceb\x06proto3"

var (
	file_techbridge_ap_governance_v1_budget_proto_rawDescOnce sync.Once
	file_techbridge_ap_governance_v1_budget_proto_rawDescData []byte
)

func file_techbridge_ap_governance_v1_budget_proto_rawDescGZIP() []byte {
	file_techbridge_ap_governance_v1_budget_proto_rawDescOnce.Do(func() {
		file_techbridge_ap_governance_v1_budget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_techbridge_ap_governance_v1_budget_proto_rawDesc), len(file_techbridge_ap_governance_v1_budget_proto_rawDesc)))
	})
	return file_techbridge_ap_governance_v1_budget_proto_rawDescData
}

var file_techbridge_ap_governance_v1_budget_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_techbridge_ap_governance_v1_budget_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_techbridge_ap_governance_v1_budget_proto_goTypes = []any{
	(Budget_Period)(0),            // 0: techbridge.ap.governance.v1.Budget.Period
	(*Budget)(nil),                // 1: techbridge.ap.governance.v1.Budget
	(*GetBudgetRequest)(nil),      // 2: techbridge.ap.governance.v1.GetBudgetRequest
	(*CreateBudgetRequest)(nil),   // 3: techbridge.ap.governance.v1.CreateBudgetRequest
	(*UpdateBudgetRequest)(nil),   // 4: techbridge.ap.governance.v1.UpdateBudgetRequest
	(*ListBudgetsRequest)(nil),    // 5: techbridge.ap.governance.v1.ListBudgetsRequest
	(*ListBudgetsResponse)(nil),   // 6: techbridge.ap.governance.v1.ListBudgetsResponse
	(*RecordSpendRequest)(nil),    // 7: techbridge.ap.governance.v1.RecordSpendRequest
	(*SpendEvent)(nil),            // 8: techbridge.ap.governance.v1.SpendEvent
	(*RecordSpendResponse)(nil),   // 9: techbridge.ap.governance.v1.RecordSpendResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 11: google.protobuf.FieldMask
}
var file_techbridge_ap_governance_v1_budget_proto_depIdxs = []int32{
	0,  // 0: techbridge.ap.governance.v1.Budget.period:type_name -> techbridge.ap.governance.v1.Budget.Period
	10, // 1: techbridge.ap.governance.v1.Budget.create_time:type_name -> google.protobuf.Timestamp
	10, // 2: techbridge.ap.governance.v1.Budget.update_time:type_name -> google.protobuf.Timestamp
	1,  // 3: techbridge.ap.governance.v1.CreateBudgetRequest.budget:type_name -> techbridge.ap.governance.v1.Budget
	1,  // 4: techbridge.ap.governance.v1.UpdateBudgetRequest.budget:type_name -> techbridge.ap.governance.v1.Budget
	11, // 5: techbridge.ap.governance.v1.UpdateBudgetRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 6: techbridge.ap.governance.v1.ListBudgetsResponse.budgets:type_name -> techbridge.ap.governance.v1.Budget
	8,  // 7: techbridge.ap.governance.v1.RecordSpendRequest.spend:type_name -> techbridge.ap.governance.v1.SpendEvent
	10, // 8: techbridge.ap.governance.v1.SpendEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2,  // 9: techbridge.ap.governance.v1.BudgetsService.GetBudget:input_type -> techbridge.ap.governance.v1.GetBudgetRequest
	3,  // 10: techbridge.ap.governance.v1.BudgetsService.CreateBudget:input_type -> techbridge.ap.governance.v1.CreateBudgetRequest
	4,  // 11: techbridge.ap.governance.v1.BudgetsService.UpdateBudget:input_type -> techbridge.ap.governance.v1.UpdateBudgetRequest
	5,  // 12: techbridge.ap.governance.v1.BudgetsService.ListBudgets:input_type -> techbridge.ap.governance.v1.ListBudgetsRequest
	7,  // 13: techbridge.ap.governance.v1.BudgetsService.RecordSpend:input_type -> techbridge.ap.governance.v1.RecordSpendRequest
	1,  // 14: techbridge.ap.governance.v1.BudgetsService.GetBudget:output_type -> techbridge.ap.governance.v1.Budget
	1,  // 15: techbridge.ap.governance.v1.BudgetsService.CreateBudget:output_type -> techbridge.ap.governance.v1.Budget
	1,  // 16: techbridge.ap.governance.v1.BudgetsService.UpdateBudget:output_type -> techbridge.ap.governance.v1.Budget
	6,  // 17: techbridge.ap.governance.v1.BudgetsService.ListBudgets:output_type -> techbridge.ap.governance.v1.ListBudgetsResponse
	9,  // 18: techbridge.ap.governance.v1.BudgetsService.RecordSpend:output_type -> techbridge.ap.governance.v1.RecordSpendResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_techbridge_ap_governance_v1_budget_proto_init() }
func file_techbridge_ap_governance_v1_budget_proto_init() {
	if File_techbridge_ap_governance_v1_budget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_techbridge_ap_governance_v1_budget_proto_rawDesc), len(file_techbridge_ap_governance_v1_budget_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techbridge_ap_governance_v1_budget_proto_goTypes,
		DependencyIndexes: file_techbridge_ap_governance_v1_budget_proto_depIdxs,
		EnumInfos:         file_techbridge_ap_governance_v1_budget_proto_enumTypes,
		MessageInfos:      file_techbridge_ap_governance_v1_budget_proto_msgTypes,
	}.Build()
	File_techbridge_ap_governance_v1_budget_proto = out.File
	file_techbridge_ap_governance_v1_budget_proto_goTypes = nil
	file_techbridge_ap_governance_v1_budget_proto_depIdxs = nil
}
