// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: techbridge/ap/governance/v1/budget.proto

package governance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BudgetsService_GetBudget_FullMethodName    = "/techbridge.ap.governance.v1.BudgetsService/GetBudget"
	BudgetsService_CreateBudget_FullMethodName = "/techbridge.ap.governance.v1.BudgetsService/CreateBudget"
	BudgetsService_UpdateBudget_FullMethodName = "/techbridge.ap.governance.v1.BudgetsService/UpdateBudget"
	BudgetsService_ListBudgets_FullMethodName  = "/techbridge.ap.governance.v1.BudgetsService/ListBudgets"
	BudgetsService_RecordSpend_FullMethodName  = "/techbridge.ap.governance.v1.BudgetsService/RecordSpend"
)

// BudgetsServiceClient is the client API for BudgetsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BudgetsService holds the spend ceilings governance decides against, and
// receives what was actually spent.
//
// A budget's scope is the organisation, optionally narrowed by product,
// user, or agent. An organisation can contain several products, so an
// organisation-wide budget (no product, user, or agent set) is broader than
// a product-specific budget.
//
// Six scope shapes are meaningful: organisation-wide, product, user, agent,
// product+user, and product+agent. A scope combining user and agent (with
// or without product) is rejected by CreateBudget and UpdateBudget, never
// silently accepted. The policy for resolving multiple applicable budgets
// that cover the same spend remains intentionally left to governance
// behavior rather than defined here.
type BudgetsServiceClient interface {
	// Returns a single budget's configuration by resource name.
	//
	// Returns the ceiling and its scope, not current spend. How spend is
	// tracked against a budget is not yet part of this contract.
	GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*Budget, error)
	// Registers a new budget.
	//
	// Rejects PERIOD_UNSPECIFIED and a scope combining user and agent.
	CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*Budget, error)
	// Updates an existing budget's configuration.
	//
	// Subject to the same period and scope-combination rules as CreateBudget.
	UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*Budget, error)
	// Lists the budgets configured for an organisation.
	ListBudgets(ctx context.Context, in *ListBudgetsRequest, opts ...grpc.CallOption) (*ListBudgetsResponse, error)
	// Records that amounts were spent, so governance can apply them to every
	// budget each is in scope for.
	//
	// Called by metering, after it has already written the corresponding
	// activities. `spend` is repeated so this works whether metering calls it
	// once per activity or once per batch.
	RecordSpend(ctx context.Context, in *RecordSpendRequest, opts ...grpc.CallOption) (*RecordSpendResponse, error)
}

type budgetsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBudgetsServiceClient(cc grpc.ClientConnInterface) BudgetsServiceClient {
	return &budgetsServiceClient{cc}
}

func (c *budgetsServiceClient) GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*Budget, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Budget)
	err := c.cc.Invoke(ctx, BudgetsService_GetBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetsServiceClient) CreateBudget(ctx context.Context, in *CreateBudgetRequest, opts ...grpc.CallOption) (*Budget, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Budget)
	err := c.cc.Invoke(ctx, BudgetsService_CreateBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetsServiceClient) UpdateBudget(ctx context.Context, in *UpdateBudgetRequest, opts ...grpc.CallOption) (*Budget, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Budget)
	err := c.cc.Invoke(ctx, BudgetsService_UpdateBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetsServiceClient) ListBudgets(ctx context.Context, in *ListBudgetsRequest, opts ...grpc.CallOption) (*ListBudgetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBudgetsResponse)
	err := c.cc.Invoke(ctx, BudgetsService_ListBudgets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetsServiceClient) RecordSpend(ctx context.Context, in *RecordSpendRequest, opts ...grpc.CallOption) (*RecordSpendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordSpendResponse)
	err := c.cc.Invoke(ctx, BudgetsService_RecordSpend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BudgetsServiceServer is the server API for BudgetsService service.
// All implementations must embed UnimplementedBudgetsServiceServer
// for forward compatibility.
//
// BudgetsService holds the spend ceilings governance decides against, and
// receives what was actually spent.
//
// A budget's scope is the organisation, optionally narrowed by product,
// user, or agent. An organisation can contain several products, so an
// organisation-wide budget (no product, user, or agent set) is broader than
// a product-specific budget.
//
// Six scope shapes are meaningful: organisation-wide, product, user, agent,
// product+user, and product+agent. A scope combining user and agent (with
// or without product) is rejected by CreateBudget and UpdateBudget, never
// silently accepted. The policy for resolving multiple applicable budgets
// that cover the same spend remains intentionally left to governance
// behavior rather than defined here.
type BudgetsServiceServer interface {
	// Returns a single budget's configuration by resource name.
	//
	// Returns the ceiling and its scope, not current spend. How spend is
	// tracked against a budget is not yet part of this contract.
	GetBudget(context.Context, *GetBudgetRequest) (*Budget, error)
	// Registers a new budget.
	//
	// Rejects PERIOD_UNSPECIFIED and a scope combining user and agent.
	CreateBudget(context.Context, *CreateBudgetRequest) (*Budget, error)
	// Updates an existing budget's configuration.
	//
	// Subject to the same period and scope-combination rules as CreateBudget.
	UpdateBudget(context.Context, *UpdateBudgetRequest) (*Budget, error)
	// Lists the budgets configured for an organisation.
	ListBudgets(context.Context, *ListBudgetsRequest) (*ListBudgetsResponse, error)
	// Records that amounts were spent, so governance can apply them to every
	// budget each is in scope for.
	//
	// Called by metering, after it has already written the corresponding
	// activities. `spend` is repeated so this works whether metering calls it
	// once per activity or once per batch.
	RecordSpend(context.Context, *RecordSpendRequest) (*RecordSpendResponse, error)
	mustEmbedUnimplementedBudgetsServiceServer()
}

// UnimplementedBudgetsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBudgetsServiceServer struct{}

func (UnimplementedBudgetsServiceServer) GetBudget(context.Context, *GetBudgetRequest) (*Budget, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBudget not implemented")
}
func (UnimplementedBudgetsServiceServer) CreateBudget(context.Context, *CreateBudgetRequest) (*Budget, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBudget not implemented")
}
func (UnimplementedBudgetsServiceServer) UpdateBudget(context.Context, *UpdateBudgetRequest) (*Budget, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBudget not implemented")
}
func (UnimplementedBudgetsServiceServer) ListBudgets(context.Context, *ListBudgetsRequest) (*ListBudgetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBudgets not implemented")
}
func (UnimplementedBudgetsServiceServer) RecordSpend(context.Context, *RecordSpendRequest) (*RecordSpendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordSpend not implemented")
}
func (UnimplementedBudgetsServiceServer) mustEmbedUnimplementedBudgetsServiceServer() {}
func (UnimplementedBudgetsServiceServer) testEmbeddedByValue()                        {}

// UnsafeBudgetsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BudgetsServiceServer will
// result in compilation errors.
type UnsafeBudgetsServiceServer interface {
	mustEmbedUnimplementedBudgetsServiceServer()
}

func RegisterBudgetsServiceServer(s grpc.ServiceRegistrar, srv BudgetsServiceServer) {
	// If the following call panics, it indicates UnimplementedBudgetsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BudgetsService_ServiceDesc, srv)
}

func _BudgetsService_GetBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetsServiceServer).GetBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetsService_GetBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetsServiceServer).GetBudget(ctx, req.(*GetBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetsService_CreateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetsServiceServer).CreateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetsService_CreateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetsServiceServer).CreateBudget(ctx, req.(*CreateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetsService_UpdateBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetsServiceServer).UpdateBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetsService_UpdateBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetsServiceServer).UpdateBudget(ctx, req.(*UpdateBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetsService_ListBudgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBudgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetsServiceServer).ListBudgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetsService_ListBudgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetsServiceServer).ListBudgets(ctx, req.(*ListBudgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetsService_RecordSpend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordSpendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetsServiceServer).RecordSpend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetsService_RecordSpend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetsServiceServer).RecordSpend(ctx, req.(*RecordSpendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BudgetsService_ServiceDesc is the grpc.ServiceDesc for BudgetsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BudgetsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "techbridge.ap.governance.v1.BudgetsService",
	HandlerType: (*BudgetsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBudget",
			Handler:    _BudgetsService_GetBudget_Handler,
		},
		{
			MethodName: "CreateBudget",
			Handler:    _BudgetsService_CreateBudget_Handler,
		},
		{
			MethodName: "UpdateBudget",
			Handler:    _BudgetsService_UpdateBudget_Handler,
		},
		{
			MethodName: "ListBudgets",
			Handler:    _BudgetsService_ListBudgets_Handler,
		},
		{
			MethodName: "RecordSpend",
			Handler:    _BudgetsService_RecordSpend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "techbridge/ap/governance/v1/budget.proto",
}
