// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: techbridge/ap/governance/v1/decision.proto

package governance

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How a call may proceed.
//
// The architecture defines all four values. The current implementation
// produces only ALLOW and DENY. NOTIFY is declared but not yet produced.
// DOWNGRADE is declared, and this contract now carries the fields it
// needs — DecideRequest.requested_provider/requested_model,
// DecideResponse.replacement_provider/replacement_model, and
// Budget.downgrade_threshold_micros with
// Budget.replacement_provider/replacement_model — but governance itself
// does not produce it yet; that is a separate, later change.
type DecideResponse_Decision int32

const (
	// Decision not specified.
	DecideResponse_DECISION_UNSPECIFIED DecideResponse_Decision = 0
	// The call may proceed.
	DecideResponse_ALLOW DecideResponse_Decision = 1
	// The call may proceed, and is flagged for someone to see.
	DecideResponse_NOTIFY DecideResponse_Decision = 2
	// The call should proceed against the replacement named in
	// replacement_provider/replacement_model instead of what was
	// requested. Not produced by any implementation yet.
	DecideResponse_DOWNGRADE DecideResponse_Decision = 3
	// The call must not proceed. Not produced by any implementation yet.
	DecideResponse_DENY DecideResponse_Decision = 4
)

// Enum value maps for DecideResponse_Decision.
var (
	DecideResponse_Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "ALLOW",
		2: "NOTIFY",
		3: "DOWNGRADE",
		4: "DENY",
	}
	DecideResponse_Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"ALLOW":                1,
		"NOTIFY":               2,
		"DOWNGRADE":            3,
		"DENY":                 4,
	}
)

func (x DecideResponse_Decision) Enum() *DecideResponse_Decision {
	p := new(DecideResponse_Decision)
	*p = x
	return p
}

func (x DecideResponse_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecideResponse_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_techbridge_ap_governance_v1_decision_proto_enumTypes[0].Descriptor()
}

func (DecideResponse_Decision) Type() protoreflect.EnumType {
	return &file_techbridge_ap_governance_v1_decision_proto_enumTypes[0]
}

func (x DecideResponse_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecideResponse_Decision.Descriptor instead.
func (DecideResponse_Decision) EnumDescriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_decision_proto_rawDescGZIP(), []int{1, 0}
}

// Request for [DecisionsService.Decide].
type DecideRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation the call would be billed to.
	// Format: `organisations/{organisation}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The agent asking to proceed.
	// Format: `organisations/{organisation}/agents/{agent}`
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	// Deprecated: no longer a budget-matching dimension. Organisation
	// identifies the customer whose spend is governed; workspace, agent and
	// user may still narrow a budget within that organisation. This field
	// remains solely for wire and stored-data compatibility — new callers
	// should leave it empty. Existing implementations may continue using it
	// until the downstream consumer update is deployed.
	//
	// Deprecated: Marked as deprecated in techbridge/ap/governance/v1/decision.proto.
	Product string `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	// The user the call would be attributed to, matching `Activity.user`.
	// Checked against that user's own cap, where one exists.
	User string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// The workspace the call would be billed to, the tenant it is for.
	// Format: `organisations/{organisation}/workspaces/{workspace}`
	//
	// Empty means the organisation's default workspace, which is what a
	// recorder written before workspaces existed asks with. A budget narrowed
	// to a workspace applies only to calls naming that one.
	Workspace string `protobuf:"bytes,5,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// The project the call would be attributed to, matching `Activity.project`.
	// Empty where the product has no such concept.
	Project string `protobuf:"bytes,6,opt,name=project,proto3" json:"project,omitempty"`
	// The provider the call would be made against, as a stable uppercase
	// token, e.g. `VERTEX_AI`, `ANTHROPIC`, `OPENAI` — the same vocabulary as
	// `PriceableUnit.provider` and `Activity.billed_by`.
	//
	// Optional: existing callers that do not yet report this leave it empty.
	// Governance evaluates ALLOW/DENY exactly as before either way; it simply
	// cannot reach a DOWNGRADE decision for a request that omits it, since a
	// downgrade is meaningless without knowing what is being downgraded from.
	RequestedProvider string `protobuf:"bytes,7,opt,name=requested_provider,json=requestedProvider,proto3" json:"requested_provider,omitempty"`
	// The model the call would be made against, as the provider names it,
	// e.g. `gemini-2.5-pro` — the same vocabulary as `Activity.model`.
	//
	// Optional, for the same reason and with the same fallback as
	// requested_provider.
	RequestedModel string `protobuf:"bytes,8,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_techbridge_ap_governance_v1_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_decision_proto_rawDescGZIP(), []int{0}
}

func (x *DecideRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DecideRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

// Deprecated: Marked as deprecated in techbridge/ap/governance/v1/decision.proto.
func (x *DecideRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *DecideRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DecideRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DecideRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DecideRequest) GetRequestedProvider() string {
	if x != nil {
		return x.RequestedProvider
	}
	return ""
}

func (x *DecideRequest) GetRequestedModel() string {
	if x != nil {
		return x.RequestedModel
	}
	return ""
}

// Response for [DecisionsService.Decide].
type DecideResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The decision.
	Decision DecideResponse_Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=techbridge.ap.governance.v1.DecideResponse_Decision" json:"decision,omitempty"`
	// Why this decision was reached, e.g. `budget exceeded`. Composed by
	// governance from a fixed vocabulary, never from a caller-supplied value.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// The version of the policy that produced this decision. Recorded so a
	// later policy change never rewrites what a past decision meant.
	PolicyVersion string `protobuf:"bytes,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// The provider to use instead of the one requested. Set only when
	// decision is DOWNGRADE, empty otherwise. Same vocabulary as
	// DecideRequest.requested_provider.
	//
	// Governance returns exactly the value configured on the budget that
	// produced this decision (Budget.replacement_provider) — this phase does
	// not search for a cheaper alternative itself.
	ReplacementProvider string `protobuf:"bytes,4,opt,name=replacement_provider,json=replacementProvider,proto3" json:"replacement_provider,omitempty"`
	// The model to use instead of the one requested. Set only when decision
	// is DOWNGRADE, empty otherwise. Same vocabulary as
	// DecideRequest.requested_model and Budget.replacement_model.
	ReplacementModel string `protobuf:"bytes,5,opt,name=replacement_model,json=replacementModel,proto3" json:"replacement_model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DecideResponse) Reset() {
	*x = DecideResponse{}
	mi := &file_techbridge_ap_governance_v1_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResponse) ProtoMessage() {}

func (x *DecideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResponse.ProtoReflect.Descriptor instead.
func (*DecideResponse) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_decision_proto_rawDescGZIP(), []int{1}
}

func (x *DecideResponse) GetDecision() DecideResponse_Decision {
	if x != nil {
		return x.Decision
	}
	return DecideResponse_DECISION_UNSPECIFIED
}

func (x *DecideResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DecideResponse) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *DecideResponse) GetReplacementProvider() string {
	if x != nil {
		return x.ReplacementProvider
	}
	return ""
}

func (x *DecideResponse) GetReplacementModel() string {
	if x != nil {
		return x.ReplacementModel
	}
	return ""
}

// Request for [DecisionsService.StreamDecisionInvalidations].
type StreamDecisionInvalidationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation to watch for budget mutations.
	// Format: `organisations/{organisation}`
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDecisionInvalidationsRequest) Reset() {
	*x = StreamDecisionInvalidationsRequest{}
	mi := &file_techbridge_ap_governance_v1_decision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDecisionInvalidationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDecisionInvalidationsRequest) ProtoMessage() {}

func (x *StreamDecisionInvalidationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_decision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDecisionInvalidationsRequest.ProtoReflect.Descriptor instead.
func (*StreamDecisionInvalidationsRequest) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_decision_proto_rawDescGZIP(), []int{2}
}

func (x *StreamDecisionInvalidationsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

// One notification that cached decisions in the given scope may be stale.
//
// Mirrors Budget's own scope fields exactly: product, user and agent are
// each optional, and an unset field means the same wider scope it means on
// Budget — e.g. product set with user and agent both unset means every
// user and agent under that product.
type DecisionInvalidation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The organisation this notification applies to.
	// Format: `organisations/{organisation}`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The product whose budget changed, if the change was scoped to one.
	Product string `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	// The user whose budget changed, if the change was scoped to one.
	User string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// The agent whose budget changed, if the change was scoped to one.
	// Format: `organisations/{organisation}/agents/{agent}`
	Agent string `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`
	// The workspace whose budget changed, if the change was scoped to one.
	// Format: `organisations/{organisation}/workspaces/{workspace}`
	Workspace string `protobuf:"bytes,5,opt,name=workspace,proto3" json:"workspace,omitempty"`
	// The project whose budget changed, if the change was scoped to one.
	Project       string `protobuf:"bytes,6,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionInvalidation) Reset() {
	*x = DecisionInvalidation{}
	mi := &file_techbridge_ap_governance_v1_decision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionInvalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionInvalidation) ProtoMessage() {}

func (x *DecisionInvalidation) ProtoReflect() protoreflect.Message {
	mi := &file_techbridge_ap_governance_v1_decision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionInvalidation.ProtoReflect.Descriptor instead.
func (*DecisionInvalidation) Descriptor() ([]byte, []int) {
	return file_techbridge_ap_governance_v1_decision_proto_rawDescGZIP(), []int{3}
}

func (x *DecisionInvalidation) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *DecisionInvalidation) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *DecisionInvalidation) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DecisionInvalidation) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *DecisionInvalidation) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DecisionInvalidation) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

var File_techbridge_ap_governance_v1_decision_proto protoreflect.FileDescriptor

const file_techbridge_ap_governance_v1_decision_proto_rawDesc = "" +
	"\n" +
	"*techbridge/ap/governance/v1/decision.proto\x12\x1btechbridge.ap.governance.v1\x1a\x1fgoogle/api/field_behavior.proto\"\x8b\x02\n" +
	"\rDecideRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x1a\n" +
	"\x05agent\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05agent\x12\x1c\n" +
	"\aproduct\x18\x03 \x01(\tB\x02\x18\x01R\aproduct\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1c\n" +
	"\tworkspace\x18\x05 \x01(\tR\tworkspace\x12\x18\n" +
	"\aproject\x18\x06 \x01(\tR\aproject\x12-\n" +
	"\x12requested_provider\x18\a \x01(\tR\x11requestedProvider\x12'\n" +
	"\x0frequested_model\x18\b \x01(\tR\x0erequestedModel\"\xd7\x02\n" +
	"\x0eDecideResponse\x12P\n" +
	"\bdecision\x18\x01 \x01(\x0e24.techbridge.ap.governance.v1.DecideResponse.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\tR\rpolicyVersion\x121\n" +
	"\x14replacement_provider\x18\x04 \x01(\tR\x13replacementProvider\x12+\n" +
	"\x11replacement_model\x18\x05 \x01(\tR\x10replacementModel\"T\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\n" +
	"\n" +
	"\x06NOTIFY\x10\x02\x12\r\n" +
	"\tDOWNGRADE\x10\x03\x12\b\n" +
	"\x04DENY\x10\x04\"B\n" +
	"\"StreamDecisionInvalidationsRequest\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\"\xb0\x01\n" +
	"\x14DecisionInvalidation\x12\x1c\n" +
	"\x06parent\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x06parent\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x14\n" +
	"\x05agent\x18\x04 \x01(\tR\x05agent\x12\x1c\n" +
	"\tworkspace\x18\x05 \x01(\tR\tworkspace\x12\x18\n" +
	"\aproject\x18\x06 \x01(\tR\aproject2\x8f\x02\n" +
	"\x10DecisionsService\x12c\n" +
	"\x06Decide\x12*.techbridge.ap.governance.v1.DecideRequest\x1a+.techbridge.ap.governance.v1.DecideResponse\"\x00\x12\x95\x01\n" +
	"\x1bStreamDecisionInvalidations\x12?.techbridge.ap.governance.v1.StreamDecisionInvalidationsRequest\x1a1.techbridge.ap.governance.v1.DecisionInvalidation\"\x000\x01B%Z#alis.build/techbridge/ap/governanceb\x06proto3"

var (
	file_techbridge_ap_governance_v1_decision_proto_rawDescOnce sync.Once
	file_techbridge_ap_governance_v1_decision_proto_rawDescData []byte
)

func file_techbridge_ap_governance_v1_decision_proto_rawDescGZIP() []byte {
	file_techbridge_ap_governance_v1_decision_proto_rawDescOnce.Do(func() {
		file_techbridge_ap_governance_v1_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_techbridge_ap_governance_v1_decision_proto_rawDesc), len(file_techbridge_ap_governance_v1_decision_proto_rawDesc)))
	})
	return file_techbridge_ap_governance_v1_decision_proto_rawDescData
}

var file_techbridge_ap_governance_v1_decision_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_techbridge_ap_governance_v1_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_techbridge_ap_governance_v1_decision_proto_goTypes = []any{
	(DecideResponse_Decision)(0),               // 0: techbridge.ap.governance.v1.DecideResponse.Decision
	(*DecideRequest)(nil),                      // 1: techbridge.ap.governance.v1.DecideRequest
	(*DecideResponse)(nil),                     // 2: techbridge.ap.governance.v1.DecideResponse
	(*StreamDecisionInvalidationsRequest)(nil), // 3: techbridge.ap.governance.v1.StreamDecisionInvalidationsRequest
	(*DecisionInvalidation)(nil),               // 4: techbridge.ap.governance.v1.DecisionInvalidation
}
var file_techbridge_ap_governance_v1_decision_proto_depIdxs = []int32{
	0, // 0: techbridge.ap.governance.v1.DecideResponse.decision:type_name -> techbridge.ap.governance.v1.DecideResponse.Decision
	1, // 1: techbridge.ap.governance.v1.DecisionsService.Decide:input_type -> techbridge.ap.governance.v1.DecideRequest
	3, // 2: techbridge.ap.governance.v1.DecisionsService.StreamDecisionInvalidations:input_type -> techbridge.ap.governance.v1.StreamDecisionInvalidationsRequest
	2, // 3: techbridge.ap.governance.v1.DecisionsService.Decide:output_type -> techbridge.ap.governance.v1.DecideResponse
	4, // 4: techbridge.ap.governance.v1.DecisionsService.StreamDecisionInvalidations:output_type -> techbridge.ap.governance.v1.DecisionInvalidation
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_techbridge_ap_governance_v1_decision_proto_init() }
func file_techbridge_ap_governance_v1_decision_proto_init() {
	if File_techbridge_ap_governance_v1_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_techbridge_ap_governance_v1_decision_proto_rawDesc), len(file_techbridge_ap_governance_v1_decision_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techbridge_ap_governance_v1_decision_proto_goTypes,
		DependencyIndexes: file_techbridge_ap_governance_v1_decision_proto_depIdxs,
		EnumInfos:         file_techbridge_ap_governance_v1_decision_proto_enumTypes,
		MessageInfos:      file_techbridge_ap_governance_v1_decision_proto_msgTypes,
	}.Build()
	File_techbridge_ap_governance_v1_decision_proto = out.File
	file_techbridge_ap_governance_v1_decision_proto_goTypes = nil
	file_techbridge_ap_governance_v1_decision_proto_depIdxs = nil
}
