// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: techbridge/ap/governance/v1/decision.proto

package governance

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DecisionsService_Decide_FullMethodName                      = "/techbridge.ap.governance.v1.DecisionsService/Decide"
	DecisionsService_StreamDecisionInvalidations_FullMethodName = "/techbridge.ap.governance.v1.DecisionsService/StreamDecisionInvalidations"
)

// DecisionsServiceClient is the client API for DecisionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DecisionsService answers whether an agent may proceed with a call it is
// about to make, before it makes it.
//
// Governance is authoritative for an organisation's spend ceiling and any
// narrower workspace, agent or user cap within it, and returns a verdict
// rather than raw budget figures — how a recorder caches and reuses that
// verdict between calls is a question for the recorder's own integration
// work, not this contract.
type DecisionsServiceClient interface {
	// Decides whether a call may proceed.
	Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error)
	// Streams a notification whenever a budget mutation may have made a
	// previously cached Decide verdict stale.
	//
	// Carries no decision data — governance remains the sole authority for
	// decision semantics, exactly as with Decide itself. A recorder that
	// receives one drops whatever it has cached matching the given scope and
	// asks Decide again the next time it is needed.
	//
	// Delivery is best effort. A recorder's existing cache TTL is what
	// actually bounds staleness: a missed or delayed notification, or the
	// stream being unavailable altogether, only means a cached verdict is
	// reused for up to that TTL — exactly as if this stream did not exist.
	// Spend recorded via RecordSpend does not trigger a notification here;
	// only budget configuration changes (CreateBudget, UpdateBudget) do.
	StreamDecisionInvalidations(ctx context.Context, in *StreamDecisionInvalidationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DecisionInvalidation], error)
}

type decisionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecisionsServiceClient(cc grpc.ClientConnInterface) DecisionsServiceClient {
	return &decisionsServiceClient{cc}
}

func (c *decisionsServiceClient) Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecideResponse)
	err := c.cc.Invoke(ctx, DecisionsService_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decisionsServiceClient) StreamDecisionInvalidations(ctx context.Context, in *StreamDecisionInvalidationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DecisionInvalidation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DecisionsService_ServiceDesc.Streams[0], DecisionsService_StreamDecisionInvalidations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDecisionInvalidationsRequest, DecisionInvalidation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionsService_StreamDecisionInvalidationsClient = grpc.ServerStreamingClient[DecisionInvalidation]

// DecisionsServiceServer is the server API for DecisionsService service.
// All implementations must embed UnimplementedDecisionsServiceServer
// for forward compatibility.
//
// DecisionsService answers whether an agent may proceed with a call it is
// about to make, before it makes it.
//
// Governance is authoritative for an organisation's spend ceiling and any
// narrower workspace, agent or user cap within it, and returns a verdict
// rather than raw budget figures — how a recorder caches and reuses that
// verdict between calls is a question for the recorder's own integration
// work, not this contract.
type DecisionsServiceServer interface {
	// Decides whether a call may proceed.
	Decide(context.Context, *DecideRequest) (*DecideResponse, error)
	// Streams a notification whenever a budget mutation may have made a
	// previously cached Decide verdict stale.
	//
	// Carries no decision data — governance remains the sole authority for
	// decision semantics, exactly as with Decide itself. A recorder that
	// receives one drops whatever it has cached matching the given scope and
	// asks Decide again the next time it is needed.
	//
	// Delivery is best effort. A recorder's existing cache TTL is what
	// actually bounds staleness: a missed or delayed notification, or the
	// stream being unavailable altogether, only means a cached verdict is
	// reused for up to that TTL — exactly as if this stream did not exist.
	// Spend recorded via RecordSpend does not trigger a notification here;
	// only budget configuration changes (CreateBudget, UpdateBudget) do.
	StreamDecisionInvalidations(*StreamDecisionInvalidationsRequest, grpc.ServerStreamingServer[DecisionInvalidation]) error
	mustEmbedUnimplementedDecisionsServiceServer()
}

// UnimplementedDecisionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecisionsServiceServer struct{}

func (UnimplementedDecisionsServiceServer) Decide(context.Context, *DecideRequest) (*DecideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedDecisionsServiceServer) StreamDecisionInvalidations(*StreamDecisionInvalidationsRequest, grpc.ServerStreamingServer[DecisionInvalidation]) error {
	return status.Error(codes.Unimplemented, "method StreamDecisionInvalidations not implemented")
}
func (UnimplementedDecisionsServiceServer) mustEmbedUnimplementedDecisionsServiceServer() {}
func (UnimplementedDecisionsServiceServer) testEmbeddedByValue()                          {}

// UnsafeDecisionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecisionsServiceServer will
// result in compilation errors.
type UnsafeDecisionsServiceServer interface {
	mustEmbedUnimplementedDecisionsServiceServer()
}

func RegisterDecisionsServiceServer(s grpc.ServiceRegistrar, srv DecisionsServiceServer) {
	// If the following call panics, it indicates UnimplementedDecisionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DecisionsService_ServiceDesc, srv)
}

func _DecisionsService_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionsServiceServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecisionsService_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionsServiceServer).Decide(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecisionsService_StreamDecisionInvalidations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDecisionInvalidationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecisionsServiceServer).StreamDecisionInvalidations(m, &grpc.GenericServerStream[StreamDecisionInvalidationsRequest, DecisionInvalidation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecisionsService_StreamDecisionInvalidationsServer = grpc.ServerStreamingServer[DecisionInvalidation]

// DecisionsService_ServiceDesc is the grpc.ServiceDesc for DecisionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecisionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "techbridge.ap.governance.v1.DecisionsService",
	HandlerType: (*DecisionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decide",
			Handler:    _DecisionsService_Decide_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDecisionInvalidations",
			Handler:       _DecisionsService_StreamDecisionInvalidations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "techbridge/ap/governance/v1/decision.proto",
}
